EVENT_TYPES = [
    # Comedy
    {"name": "Open Mic Nights", "category": "Comedy", "keywords": "open mic, comedy, stand-up"},
    {"name": "Comedy Club Headliners", "category": "Comedy", "keywords": "comedy club, headliner, stand-up"},
    {"name": "One-Person Shows", "category": "Comedy", "keywords": "one-person, solo, comedy show"},
    {"name": "Sketch Comedy Performances", "category": "Comedy", "keywords": "sketch, comedy, performance"},
    {"name": "Short-Form Improv", "category": "Comedy", "keywords": "improv, short-form, whose line"},
    {"name": "Long-Form Improv", "category": "Comedy", "keywords": "improv, long-form, narrative"},
    {"name": "Musical Improv", "category": "Comedy", "keywords": "improv, musical, comedy"},
    # Music — Popular genres
    {"name": "Jazz Concert", "category": "Music", "keywords": "jazz, bebop, swing, blues, jazz club"},
    {"name": "Hip-Hop / Rap Concert", "category": "Music", "keywords": "hip-hop, hip hop, rap, trap, drill"},
    {"name": "Rock Concert", "category": "Music", "keywords": "rock, punk, metal, indie rock, alternative, grunge"},
    {"name": "Pop Concert", "category": "Music", "keywords": "pop concert, pop music, pop show"},
    {"name": "Electronic / DJ Set", "category": "Music", "keywords": "dj set, dj, electronic, edm, techno, house music, rave, club night, dnb, drum and bass, ambient"},
    {"name": "R&B / Soul Concert", "category": "Music", "keywords": "r&b, soul, neo-soul, motown, funk"},
    {"name": "Country Concert", "category": "Music", "keywords": "country, bluegrass, americana, folk"},
    {"name": "Latin Concert", "category": "Music", "keywords": "latin, salsa, reggaeton, cumbia, bachata, merengue"},
    {"name": "Reggae / Calypso Concert", "category": "Music", "keywords": "reggae, calypso, dancehall, ska"},
    {"name": "Gospel Concert", "category": "Music", "keywords": "gospel, christian music, worship concert"},
    # Music — Classical
    {"name": "Symphony Orchestral Performances", "category": "Music", "keywords": "symphony, orchestra, classical"},
    {"name": "Pops Concerts", "category": "Music", "keywords": "pops, orchestra, classical"},
    {"name": "Concerto Performances", "category": "Music", "keywords": "concerto, classical, orchestra"},
    {"name": "String Quartets", "category": "Music", "keywords": "string quartet, chamber music, classical"},
    {"name": "Piano Trios", "category": "Music", "keywords": "piano trio, chamber music, classical"},
    {"name": "Woodwind Ensembles", "category": "Music", "keywords": "woodwind, chamber music, classical"},
    {"name": "Solo Recitals", "category": "Music", "keywords": "solo, recital, classical"},
    {"name": "Fully Staged Opera", "category": "Music", "keywords": "opera, staged, classical"},
    {"name": "Concert Versions of Operas", "category": "Music", "keywords": "opera, concert, classical"},
    {"name": "Baroque Orchestras", "category": "Music", "keywords": "baroque, early music, classical"},
    {"name": "Renaissance Vocal Ensembles", "category": "Music", "keywords": "renaissance, early music, vocal"},
    # Dance
    {"name": "Classical Ballet", "category": "Dance", "keywords": "ballet, classical, dance"},
    {"name": "Neoclassical Ballet", "category": "Dance", "keywords": "ballet, neoclassical, dance"},
    {"name": "Contemporary Ballet", "category": "Dance", "keywords": "ballet, contemporary, dance"},
    {"name": "Modern Dance", "category": "Dance", "keywords": "modern dance, contemporary"},
    {"name": "Post-Modern Dance", "category": "Dance", "keywords": "post-modern, dance, contemporary"},
    {"name": "Fusion Dance", "category": "Dance", "keywords": "fusion, dance, contemporary"},
    {"name": "Flamenco", "category": "Dance", "keywords": "flamenco, world dance, spanish"},
    {"name": "Bharatanatyam", "category": "Dance", "keywords": "bharatanatyam, indian, world dance"},
    {"name": "Irish Step Dance", "category": "Dance", "keywords": "irish, step dance, world dance"},
    {"name": "African Dance", "category": "Dance", "keywords": "african, world dance"},
    {"name": "Theatrical Jazz Dance", "category": "Dance", "keywords": "jazz dance, theatrical"},
    {"name": "Lyrical Jazz Dance", "category": "Dance", "keywords": "jazz dance, lyrical"},
    # Festival
    {"name": "Genre-Specific Music Festivals", "category": "Festival", "keywords": "music festival, genre"},
    {"name": "Multi-Genre Music Festivals", "category": "Festival", "keywords": "music festival, multi-genre"},
    {"name": "Indie Music Festivals", "category": "Festival", "keywords": "music festival, indie"},
    {"name": "Restaurant Weeks", "category": "Festival", "keywords": "food festival, restaurant"},
    {"name": "Street Food Fairs", "category": "Festival", "keywords": "food festival, street food"},
    {"name": "Ingredient Celebrations", "category": "Festival", "keywords": "food festival, ingredient"},
    {"name": "Heritage Festivals", "category": "Festival", "keywords": "cultural festival, heritage"},
    {"name": "Ethnic Celebrations", "category": "Festival", "keywords": "cultural festival, ethnic"},
    {"name": "Folklore Events", "category": "Festival", "keywords": "cultural festival, folklore"},
    {"name": "Film Festivals", "category": "Festival", "keywords": "film festival, cinema"},
    {"name": "Multi-Disciplinary Arts Festivals", "category": "Festival", "keywords": "arts festival, multi-disciplinary"},
    {"name": "Theater Festivals", "category": "Festival", "keywords": "theater festival, arts"},
    {"name": "Literary Festivals", "category": "Festival", "keywords": "literary festival, books"},
    # Art — Theatre
    {"name": "Broadway Show", "category": "Art", "keywords": "broadway, off-broadway, musical theatre, musical theater, west end"},
    {"name": "Play / Drama", "category": "Art", "keywords": "play, drama, theatre, staged reading, one-act"},
    # Art — Galleries
    {"name": "Commercial Gallery Exhibitions", "category": "Art", "keywords": "gallery, commercial, art exhibition"},
    {"name": "Artist-Run Space Exhibitions", "category": "Art", "keywords": "artist-run, gallery, art exhibition"},
    {"name": "Cooperative Gallery Exhibitions", "category": "Art", "keywords": "cooperative, gallery, art exhibition"},
    {"name": "Museum Private Previews", "category": "Art", "keywords": "museum, preview, art exhibition"},
    {"name": "Museum Public Opening Receptions", "category": "Art", "keywords": "museum, opening, art exhibition"},
    {"name": "Special Museum Exhibitions", "category": "Art", "keywords": "museum, special exhibition, art"},
    {"name": "Art Fairs", "category": "Art", "keywords": "art fair, galleries, commercial"},
    {"name": "Outdoor Sculptures", "category": "Art", "keywords": "public art, sculpture, installation"},
    {"name": "Murals", "category": "Art", "keywords": "public art, mural, installation"},
    {"name": "Interactive Art Installations", "category": "Art", "keywords": "public art, interactive, installation"},
    # Film
    {"name": "International Film Festivals", "category": "Film", "keywords": "film festival, international, cinema"},
    {"name": "Genre-Specific Film Festivals", "category": "Film", "keywords": "film festival, genre, cinema"},
    {"name": "Short Film Festivals", "category": "Film", "keywords": "film festival, short films, cinema"},
    {"name": "Red Carpet Premieres", "category": "Film", "keywords": "premiere, red carpet, cinema"},
    {"name": "Advance Screenings", "category": "Film", "keywords": "premiere, advance screening, cinema"},
    {"name": "Director Retrospectives", "category": "Film", "keywords": "retrospective, director, cinema"},
    {"name": "Actor Retrospectives", "category": "Film", "keywords": "retrospective, actor, cinema"},
    {"name": "Classic Film Series", "category": "Film", "keywords": "retrospective, classic films, cinema"},
    {"name": "Art House Cinema Screenings", "category": "Film", "keywords": "independent film, art house, cinema"},
    {"name": "Community Film Screenings", "category": "Film", "keywords": "independent film, community, cinema"},
    # Literature
    {"name": "Author Talks", "category": "Literature", "keywords": "author, talk, book, literary"},
    {"name": "Panel Discussions", "category": "Literature", "keywords": "panel, discussion, book, literary"},
    {"name": "Poetry Slams", "category": "Literature", "keywords": "poetry, slam, literary"},
    {"name": "Book Launches", "category": "Literature", "keywords": "book launch, author, literary"},
    {"name": "Library Author Visits", "category": "Literature", "keywords": "library, author, book"},
    {"name": "Book Clubs", "category": "Literature", "keywords": "book club, library, literary"},
    # Food & Drink
    {"name": "Wine Tastings", "category": "Food & Drink", "keywords": "wine, tasting, food"},
    {"name": "Beer Samplings", "category": "Food & Drink", "keywords": "beer, tasting, food"},
    {"name": "Spirit Tastings", "category": "Food & Drink", "keywords": "spirit, tasting, food"},
    {"name": "Cheese Tastings", "category": "Food & Drink", "keywords": "cheese, tasting, food"},
    {"name": "Chef Demonstrations", "category": "Food & Drink", "keywords": "chef, demonstration, culinary"},
    {"name": "Cooking Competitions", "category": "Food & Drink", "keywords": "cooking, competition, culinary"},
    {"name": "Regional Wine Celebrations", "category": "Food & Drink", "keywords": "wine festival, regional"},
    {"name": "Vineyard Tours", "category": "Food & Drink", "keywords": "wine, vineyard, tour"},
    {"name": "Craft Beer Events", "category": "Food & Drink", "keywords": "beer festival, craft beer"},
    {"name": "Brewery Tours", "category": "Food & Drink", "keywords": "beer, brewery, tour"},
    {"name": "Farmers Markets", "category": "Food & Drink", "keywords": "farmers market, local produce, food"},
    # Charity
    {"name": "Formal Fundraising Galas", "category": "Charity", "keywords": "gala, fundraising, charity"},
    {"name": "Benefit Concerts", "category": "Charity", "keywords": "benefit, concert, charity"},
    {"name": "Fundraising Dinners", "category": "Charity", "keywords": "fundraising, dinner, charity"},
    {"name": "Charity Auctions", "category": "Charity", "keywords": "auction, charity, fundraising"},
    {"name": "Charity Walks", "category": "Charity", "keywords": "walk, charity, fundraising"},
    {"name": "Charity Runs", "category": "Charity", "keywords": "run, charity, fundraising"},
    # Political
    {"name": "Campaign Events", "category": "Political", "keywords": "campaign, political, rally"},
    {"name": "Voter Mobilization Drives", "category": "Political", "keywords": "voter, mobilization, political"},
    {"name": "Protests", "category": "Political", "keywords": "protest, activist, political"},
    {"name": "Marches", "category": "Political", "keywords": "march, activist, political"},
    {"name": "Demonstrations", "category": "Political", "keywords": "demonstration, activist, political"},
    {"name": "Advocacy Events", "category": "Political", "keywords": "advocacy, activist, political"},
    {"name": "Town Hall Meetings", "category": "Political", "keywords": "town hall, political, public forum"},
    # Religious
    {"name": "Pilgrimages", "category": "Religious", "keywords": "pilgrimage, religious, spiritual"},
    {"name": "Church Services", "category": "Religious", "keywords": "church, service, religious"},
    {"name": "Religious Community Gatherings", "category": "Religious", "keywords": "religious, community, gathering"},
    {"name": "Religious Education Programs", "category": "Religious", "keywords": "religious, education, program"},
    {"name": "Religious Conventions", "category": "Religious", "keywords": "religious, convention, gathering"},
    {"name": "Spiritual Retreats", "category": "Religious", "keywords": "retreat, spiritual, religious"},
    # Technology
    {"name": "Tech Conference", "category": "Technology", "keywords": "tech conference, technology, developer, software, design, web, digital, innovation"},
    {"name": "Consumer Electronics Shows", "category": "Technology", "keywords": "tech expo, electronics, technology"},
    {"name": "Startup Showcases", "category": "Technology", "keywords": "startup, showcase, technology"},
    {"name": "AI Tech Conferences", "category": "Technology", "keywords": "tech conference, AI, technology"},
    {"name": "Cybersecurity Conferences", "category": "Technology", "keywords": "tech conference, cybersecurity, technology"},
    # Career
    {"name": "Job Fairs", "category": "Career", "keywords": "job fair, career, recruitment"},
    {"name": "Networking Expos", "category": "Career", "keywords": "networking, career, professional"},
    {"name": "Industry-Specific Career Events", "category": "Career", "keywords": "career, industry-specific, professional"},
    # Workshop
    {"name": "Photography Workshops", "category": "Workshop", "keywords": "workshop, photography, skill-building"},
    {"name": "Writing Workshops", "category": "Workshop", "keywords": "workshop, writing, skill-building"},
    {"name": "Coding Bootcamps", "category": "Workshop", "keywords": "workshop, coding, skill-building"},
    {"name": "Professional Development Courses", "category": "Workshop", "keywords": "workshop, professional, certification"},
    {"name": "Industry Certifications", "category": "Workshop", "keywords": "certification, professional, workshop"},
    # Academic
    {"name": "Research Presentations", "category": "Academic", "keywords": "academic, research, conference"},
    {"name": "University Symposiums", "category": "Academic", "keywords": "academic, symposium, university"},
    {"name": "Guest Speaker Events", "category": "Academic", "keywords": "academic, guest speaker, lecture"},
    # Fitness
    {"name": "Marathons", "category": "Fitness", "keywords": "marathon, running, fitness"},
    {"name": "Yoga Retreats", "category": "Fitness", "keywords": "yoga, retreat, fitness"},
    {"name": "CrossFit Competitions", "category": "Fitness", "keywords": "crossfit, competition, fitness"},
    {"name": "Cycling Races", "category": "Fitness", "keywords": "cycling, race, fitness"},
    {"name": "Organized Cycling Rides", "category": "Fitness", "keywords": "cycling, ride, fitness"},
    {"name": "Charity Bike Tours", "category": "Fitness", "keywords": "cycling, charity, tour"},
    # Automotive
    {"name": "Auto Expos", "category": "Automotive", "keywords": "car show, auto expo, automotive"},
    {"name": "Vintage Car Exhibitions", "category": "Automotive", "keywords": "car show, vintage, automotive"},
    {"name": "Custom Car Shows", "category": "Automotive", "keywords": "car show, custom, automotive"},
    # Craft
    {"name": "Handmade Goods Markets", "category": "Craft", "keywords": "craft fair, handmade, artisan"},
    {"name": "Artisan Events", "category": "Craft", "keywords": "craft fair, artisan, handmade"},
    # Parade
    {"name": "Holiday Parades", "category": "Parade", "keywords": "parade, holiday, celebration"},
    {"name": "Pride Parades", "category": "Parade", "keywords": "parade, pride, LGBTQ"},
    {"name": "Cultural Celebrations", "category": "Parade", "keywords": "parade, cultural, celebration"},
    # Theme Park
    {"name": "Seasonal Theme Park Celebrations", "category": "Theme Park", "keywords": "theme park, seasonal, celebration"},
    {"name": "Theme Park Nighttime Shows", "category": "Theme Park", "keywords": "theme park, nighttime, show"},
    {"name": "Fireworks Displays", "category": "Theme Park", "keywords": "fireworks, theme park, show"},
    {"name": "Light Shows", "category": "Theme Park", "keywords": "light show, theme park, show"},
    {"name": "Water Spectaculars", "category": "Theme Park", "keywords": "water show, theme park, spectacular"},
    # Outdoor
    {"name": "Hiking Meetups", "category": "Outdoor", "keywords": "hiking, meetup, outdoor adventure"},
    {"name": "Survival Workshops", "category": "Outdoor", "keywords": "survival, workshop, outdoor adventure"},
    {"name": "Camping Rallies", "category": "Outdoor", "keywords": "camping, rally, outdoor adventure"},
    {"name": "Rock Climbing Competitions", "category": "Outdoor", "keywords": "rock climbing, competition, outdoor adventure"},
    {"name": "Guided Rock Climbs", "category": "Outdoor", "keywords": "rock climbing, guided, outdoor adventure"},
    # Gaming
    {"name": "Board Game Conventions", "category": "Gaming", "keywords": "board games, convention, gaming"},
    {"name": "eSports Tournaments", "category": "Gaming", "keywords": "esports, tournament, gaming"},
    {"name": "Video Game Expos", "category": "Gaming", "keywords": "video games, expo, gaming"},
    {"name": "Tabletop RPG Events", "category": "Gaming", "keywords": "RPG, tabletop, gaming"},
    # Pet
    {"name": "Dog Shows", "category": "Pet", "keywords": "dog show, pet, competition"},
    {"name": "Dog Agility Trials", "category": "Pet", "keywords": "dog, agility, pet, competition"},
    {"name": "Cat Shows", "category": "Pet", "keywords": "cat show, pet, competition"},
    {"name": "Pet Adoption Events", "category": "Pet", "keywords": "pet adoption, animal, shelter"},
    # Home & Garden
    {"name": "Home Improvement Expos", "category": "Home & Garden", "keywords": "home improvement, expo, renovation"},
    {"name": "Gardening Festivals", "category": "Home & Garden", "keywords": "gardening, festival, plants"},
    {"name": "Plant Sales", "category": "Home & Garden", "keywords": "plants, sale, gardening"},
    {"name": "Landscaping Demonstrations", "category": "Home & Garden", "keywords": "landscaping, demonstration, gardening"},
    # Sports
    {"name": "Sports Event", "category": "Sports", "keywords": "sports, match, game"},
    {"name": "Baseball Game", "category": "Sports", "keywords": "baseball, mlb, cubs, yankees, dodgers, red sox"},
    {"name": "Basketball Game", "category": "Sports", "keywords": "basketball, nba, lakers, celtics, bulls"},
    {"name": "American Football Game", "category": "Sports", "keywords": "football, nfl, super bowl, touchdown"},
    {"name": "Soccer Match", "category": "Sports", "keywords": "soccer, football, mls, premier league, fifa"},
    {"name": "Hockey Game", "category": "Sports", "keywords": "hockey, nhl, ice hockey, puck"},
    {"name": "Tennis Match", "category": "Sports", "keywords": "tennis, atp, wta, grand slam"},
    {"name": "Golf Tournament", "category": "Sports", "keywords": "golf, pga, tournament"},
    {"name": "Boxing / MMA Event", "category": "Sports", "keywords": "boxing, mma, ufc, fight night"},
    {"name": "Wrestling Event", "category": "Sports", "keywords": "wrestling, wwe, aew"},
    {"name": "Athletics / Track & Field", "category": "Sports", "keywords": "track, field, athletics, sprint"},
]
