"""
Seed 1,317 OECD cities (population >= 100k) into the Cities table.
Run: python3 scripts/seed_cities.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database import SessionLocal
from app.models import City

CITIES = [
    # Australia
    ("Adelaide","Australia","Australia/Adelaide"),("Bendigo","Australia","Australia/Melbourne"),
    ("Brisbane","Australia","Australia/Brisbane"),("Cairns","Australia","Australia/Brisbane"),
    ("Canberra","Australia","Australia/Sydney"),("Darwin","Australia","Australia/Darwin"),
    ("Geelong","Australia","Australia/Melbourne"),("Gold Coast","Australia","Australia/Brisbane"),
    ("Hobart","Australia","Australia/Hobart"),("Launceston","Australia","Australia/Hobart"),
    ("Logan City","Australia","Australia/Brisbane"),("Melbourne","Australia","Australia/Melbourne"),
    ("Newcastle","Australia","Australia/Sydney"),("Perth","Australia","Australia/Perth"),
    ("Sydney","Australia","Australia/Sydney"),("Toowoomba","Australia","Australia/Brisbane"),
    ("Townsville","Australia","Australia/Brisbane"),
    # Austria
    ("Graz","Austria","Europe/Vienna"),("Innsbruck","Austria","Europe/Vienna"),
    ("Linz","Austria","Europe/Vienna"),("Salzburg","Austria","Europe/Vienna"),
    ("Vienna","Austria","Europe/Vienna"),
    # Belgium
    ("Antwerp","Belgium","Europe/Brussels"),("Bruges","Belgium","Europe/Brussels"),
    ("Brussels","Belgium","Europe/Brussels"),("Charleroi","Belgium","Europe/Brussels"),
    ("Ghent","Belgium","Europe/Brussels"),("Liège","Belgium","Europe/Brussels"),
    ("Namur","Belgium","Europe/Brussels"),
    # Canada
    ("Abbotsford","Canada","America/Vancouver"),("Barrie","Canada","America/Toronto"),
    ("Brampton","Canada","America/Toronto"),("Burlington","Canada","America/Toronto"),
    ("Burnaby","Canada","America/Vancouver"),("Calgary","Canada","America/Edmonton"),
    ("Cambridge","Canada","America/Toronto"),("Coquitlam","Canada","America/Vancouver"),
    ("Edmonton","Canada","America/Edmonton"),("Gatineau","Canada","America/Toronto"),
    ("Greater Sudbury","Canada","America/Toronto"),("Guelph","Canada","America/Toronto"),
    ("Halifax","Canada","America/Halifax"),("Hamilton","Canada","America/Toronto"),
    ("Kelowna","Canada","America/Vancouver"),("Kingston","Canada","America/Toronto"),
    ("Kitchener","Canada","America/Toronto"),("Laval","Canada","America/Toronto"),
    ("London","Canada","America/Toronto"),("Longueuil","Canada","America/Toronto"),
    ("Markham","Canada","America/Toronto"),("Mississauga","Canada","America/Toronto"),
    ("Montréal","Canada","America/Toronto"),("Oakville","Canada","America/Toronto"),
    ("Oshawa","Canada","America/Toronto"),("Ottawa","Canada","America/Toronto"),
    ("Québec","Canada","America/Toronto"),("Regina","Canada","America/Regina"),
    ("Richmond","Canada","America/Vancouver"),("Richmond Hill","Canada","America/Toronto"),
    ("Saskatoon","Canada","America/Regina"),("Sherbrooke","Canada","America/Toronto"),
    ("St. Catharines","Canada","America/Toronto"),("Surrey","Canada","America/Vancouver"),
    ("Toronto","Canada","America/Toronto"),("Vancouver","Canada","America/Vancouver"),
    ("Vaughan","Canada","America/Toronto"),("Victoria","Canada","America/Vancouver"),
    ("Windsor","Canada","America/Toronto"),("Winnipeg","Canada","America/Winnipeg"),
    # Chile
    ("Antofagasta","Chile","America/Santiago"),("Arica","Chile","America/Santiago"),
    ("Concepción","Chile","America/Santiago"),("Iquique","Chile","America/Santiago"),
    ("La Serena","Chile","America/Santiago"),("Puente Alto","Chile","America/Santiago"),
    ("Puerto Montt","Chile","America/Santiago"),("Rancagua","Chile","America/Santiago"),
    ("Santiago","Chile","America/Santiago"),("Talca","Chile","America/Santiago"),
    ("Temuco","Chile","America/Santiago"),("Valparaíso","Chile","America/Santiago"),
    ("Viña del Mar","Chile","America/Santiago"),
    # Colombia
    ("Barranquilla","Colombia","America/Bogota"),("Bogotá","Colombia","America/Bogota"),
    ("Bucaramanga","Colombia","America/Bogota"),("Cali","Colombia","America/Bogota"),
    ("Cartagena","Colombia","America/Bogota"),("Cúcuta","Colombia","America/Bogota"),
    ("Ibagué","Colombia","America/Bogota"),("Manizales","Colombia","America/Bogota"),
    ("Medellín","Colombia","America/Bogota"),("Montería","Colombia","America/Bogota"),
    ("Pereira","Colombia","America/Bogota"),("Santa Marta","Colombia","America/Bogota"),
    ("Valledupar","Colombia","America/Bogota"),("Villavicencio","Colombia","America/Bogota"),
    # Costa Rica
    ("San José","Costa Rica","America/Costa_Rica"),
    # Czechia
    ("Brno","Czechia","Europe/Prague"),("Ostrava","Czechia","Europe/Prague"),
    ("Pilsen","Czechia","Europe/Prague"),("Prague","Czechia","Europe/Prague"),
    # Denmark
    ("Aalborg","Denmark","Europe/Copenhagen"),("Copenhagen","Denmark","Europe/Copenhagen"),
    ("Odense","Denmark","Europe/Copenhagen"),("Aarhus","Denmark","Europe/Copenhagen"),
    # Estonia
    ("Tallinn","Estonia","Europe/Tallinn"),("Tartu","Estonia","Europe/Tallinn"),
    # Finland
    ("Espoo","Finland","Europe/Helsinki"),("Helsinki","Finland","Europe/Helsinki"),
    ("Oulu","Finland","Europe/Helsinki"),("Tampere","Finland","Europe/Helsinki"),
    ("Turku","Finland","Europe/Helsinki"),("Vantaa","Finland","Europe/Helsinki"),
    # France
    ("Aix-en-Provence","France","Europe/Paris"),("Amiens","France","Europe/Paris"),
    ("Angers","France","Europe/Paris"),("Besançon","France","Europe/Paris"),
    ("Bordeaux","France","Europe/Paris"),("Brest","France","Europe/Paris"),
    ("Caen","France","Europe/Paris"),("Clermont-Ferrand","France","Europe/Paris"),
    ("Dijon","France","Europe/Paris"),("Grenoble","France","Europe/Paris"),
    ("Le Havre","France","Europe/Paris"),("Le Mans","France","Europe/Paris"),
    ("Lille","France","Europe/Paris"),("Limoges","France","Europe/Paris"),
    ("Lyon","France","Europe/Paris"),("Marseille","France","Europe/Paris"),
    ("Metz","France","Europe/Paris"),("Montpellier","France","Europe/Paris"),
    ("Mulhouse","France","Europe/Paris"),("Nancy","France","Europe/Paris"),
    ("Nantes","France","Europe/Paris"),("Nice","France","Europe/Paris"),
    ("Nîmes","France","Europe/Paris"),("Orléans","France","Europe/Paris"),
    ("Paris","France","Europe/Paris"),("Perpignan","France","Europe/Paris"),
    ("Reims","France","Europe/Paris"),("Rennes","France","Europe/Paris"),
    ("Rouen","France","Europe/Paris"),("Saint-Étienne","France","Europe/Paris"),
    ("Strasbourg","France","Europe/Paris"),("Toulon","France","Europe/Paris"),
    ("Toulouse","France","Europe/Paris"),("Tours","France","Europe/Paris"),
    ("Villeurbanne","France","Europe/Paris"),
    # Germany
    ("Aachen","Germany","Europe/Berlin"),("Augsburg","Germany","Europe/Berlin"),
    ("Berlin","Germany","Europe/Berlin"),("Bielefeld","Germany","Europe/Berlin"),
    ("Bochum","Germany","Europe/Berlin"),("Bonn","Germany","Europe/Berlin"),
    ("Braunschweig","Germany","Europe/Berlin"),("Bremen","Germany","Europe/Berlin"),
    ("Chemnitz","Germany","Europe/Berlin"),("Darmstadt","Germany","Europe/Berlin"),
    ("Dortmund","Germany","Europe/Berlin"),("Dresden","Germany","Europe/Berlin"),
    ("Duisburg","Germany","Europe/Berlin"),("Düsseldorf","Germany","Europe/Berlin"),
    ("Erfurt","Germany","Europe/Berlin"),("Essen","Germany","Europe/Berlin"),
    ("Frankfurt am Main","Germany","Europe/Berlin"),("Freiburg","Germany","Europe/Berlin"),
    ("Gelsenkirchen","Germany","Europe/Berlin"),("Göttingen","Germany","Europe/Berlin"),
    ("Hagen","Germany","Europe/Berlin"),("Halle","Germany","Europe/Berlin"),
    ("Hamburg","Germany","Europe/Berlin"),("Hannover","Germany","Europe/Berlin"),
    ("Heidelberg","Germany","Europe/Berlin"),("Heilbronn","Germany","Europe/Berlin"),
    ("Ingolstadt","Germany","Europe/Berlin"),("Jena","Germany","Europe/Berlin"),
    ("Karlsruhe","Germany","Europe/Berlin"),("Kassel","Germany","Europe/Berlin"),
    ("Kiel","Germany","Europe/Berlin"),("Koblenz","Germany","Europe/Berlin"),
    ("Krefeld","Germany","Europe/Berlin"),("Cologne","Germany","Europe/Berlin"),
    ("Leipzig","Germany","Europe/Berlin"),("Leverkusen","Germany","Europe/Berlin"),
    ("Lübeck","Germany","Europe/Berlin"),("Magdeburg","Germany","Europe/Berlin"),
    ("Mainz","Germany","Europe/Berlin"),("Mannheim","Germany","Europe/Berlin"),
    ("Munich","Germany","Europe/Berlin"),("Münster","Germany","Europe/Berlin"),
    ("Neuss","Germany","Europe/Berlin"),("Nuremberg","Germany","Europe/Berlin"),
    ("Oberhausen","Germany","Europe/Berlin"),("Oldenburg","Germany","Europe/Berlin"),
    ("Osnabrück","Germany","Europe/Berlin"),("Paderborn","Germany","Europe/Berlin"),
    ("Potsdam","Germany","Europe/Berlin"),("Regensburg","Germany","Europe/Berlin"),
    ("Rostock","Germany","Europe/Berlin"),("Saarbrücken","Germany","Europe/Berlin"),
    ("Solingen","Germany","Europe/Berlin"),("Stuttgart","Germany","Europe/Berlin"),
    ("Ulm","Germany","Europe/Berlin"),("Wiesbaden","Germany","Europe/Berlin"),
    ("Wolfsburg","Germany","Europe/Berlin"),("Wuppertal","Germany","Europe/Berlin"),
    ("Würzburg","Germany","Europe/Berlin"),
    # Greece
    ("Athens","Greece","Europe/Athens"),("Thessaloniki","Greece","Europe/Athens"),
    ("Patras","Greece","Europe/Athens"),("Heraklion","Greece","Europe/Athens"),
    ("Larissa","Greece","Europe/Athens"),("Piraeus","Greece","Europe/Athens"),
    # Hungary
    ("Budapest","Hungary","Europe/Budapest"),("Debrecen","Hungary","Europe/Budapest"),
    ("Győr","Hungary","Europe/Budapest"),("Miskolc","Hungary","Europe/Budapest"),
    ("Pécs","Hungary","Europe/Budapest"),("Szeged","Hungary","Europe/Budapest"),
    # Iceland
    ("Reykjavík","Iceland","Atlantic/Reykjavik"),
    # Ireland
    ("Cork","Ireland","Europe/Dublin"),("Dublin","Ireland","Europe/Dublin"),
    # Israel
    ("Ashdod","Israel","Asia/Jerusalem"),("Beersheba","Israel","Asia/Jerusalem"),
    ("Haifa","Israel","Asia/Jerusalem"),("Jerusalem","Israel","Asia/Jerusalem"),
    ("Netanya","Israel","Asia/Jerusalem"),("Ramat Gan","Israel","Asia/Jerusalem"),
    ("Tel Aviv","Israel","Asia/Jerusalem"),
    # Italy
    ("Bari","Italy","Europe/Rome"),("Bologna","Italy","Europe/Rome"),
    ("Brescia","Italy","Europe/Rome"),("Catania","Italy","Europe/Rome"),
    ("Florence","Italy","Europe/Rome"),("Genoa","Italy","Europe/Rome"),
    ("Messina","Italy","Europe/Rome"),("Milan","Italy","Europe/Rome"),
    ("Modena","Italy","Europe/Rome"),("Naples","Italy","Europe/Rome"),
    ("Padova","Italy","Europe/Rome"),("Palermo","Italy","Europe/Rome"),
    ("Parma","Italy","Europe/Rome"),("Perugia","Italy","Europe/Rome"),
    ("Prato","Italy","Europe/Rome"),("Reggio Calabria","Italy","Europe/Rome"),
    ("Rome","Italy","Europe/Rome"),("Salerno","Italy","Europe/Rome"),
    ("Taranto","Italy","Europe/Rome"),("Trieste","Italy","Europe/Rome"),
    ("Turin","Italy","Europe/Rome"),("Verona","Italy","Europe/Rome"),
    # Japan
    ("Tokyo","Japan","Asia/Tokyo"),("Yokohama","Japan","Asia/Tokyo"),
    ("Osaka","Japan","Asia/Tokyo"),("Nagoya","Japan","Asia/Tokyo"),
    ("Sapporo","Japan","Asia/Tokyo"),("Kobe","Japan","Asia/Tokyo"),
    ("Kyoto","Japan","Asia/Tokyo"),("Fukuoka","Japan","Asia/Tokyo"),
    ("Kawasaki","Japan","Asia/Tokyo"),("Hiroshima","Japan","Asia/Tokyo"),
    ("Sendai","Japan","Asia/Tokyo"),("Kitakyushu","Japan","Asia/Tokyo"),
    ("Chiba","Japan","Asia/Tokyo"),("Sakai","Japan","Asia/Tokyo"),
    ("Kumamoto","Japan","Asia/Tokyo"),("Okayama","Japan","Asia/Tokyo"),
    ("Sagamihara","Japan","Asia/Tokyo"),("Hamamatsu","Japan","Asia/Tokyo"),
    ("Niigata","Japan","Asia/Tokyo"),("Shizuoka","Japan","Asia/Tokyo"),
    ("Funabashi","Japan","Asia/Tokyo"),("Hachioji","Japan","Asia/Tokyo"),
    ("Kagoshima","Japan","Asia/Tokyo"),("Matsuyama","Japan","Asia/Tokyo"),
    # South Korea
    ("Seoul","South Korea","Asia/Seoul"),("Busan","South Korea","Asia/Seoul"),
    ("Incheon","South Korea","Asia/Seoul"),("Daegu","South Korea","Asia/Seoul"),
    ("Daejeon","South Korea","Asia/Seoul"),("Gwangju","South Korea","Asia/Seoul"),
    ("Suwon","South Korea","Asia/Seoul"),("Ulsan","South Korea","Asia/Seoul"),
    ("Goyang","South Korea","Asia/Seoul"),("Seongnam","South Korea","Asia/Seoul"),
    # Latvia
    ("Riga","Latvia","Europe/Riga"),
    # Lithuania
    ("Kaunas","Lithuania","Europe/Vilnius"),("Vilnius","Lithuania","Europe/Vilnius"),
    # Mexico
    ("Mexico City","Mexico","America/Mexico_City"),("Ecatepec","Mexico","America/Mexico_City"),
    ("Guadalajara","Mexico","America/Mexico_City"),("Tijuana","Mexico","America/Tijuana"),
    ("Monterrey","Mexico","America/Monterrey"),("Puebla","Mexico","America/Mexico_City"),
    ("León","Mexico","America/Mexico_City"),("Juárez","Mexico","America/Ojinaga"),
    ("Torreón","Mexico","America/Matamoros"),("San Luis Potosí","Mexico","America/Mexico_City"),
    ("Mérida","Mexico","America/Merida"),("Mexicali","Mexico","America/Tijuana"),
    ("Aguascalientes","Mexico","America/Mexico_City"),("Cuernavaca","Mexico","America/Mexico_City"),
    ("Chihuahua","Mexico","America/Chihuahua"),("Saltillo","Mexico","America/Matamoros"),
    ("Zapopan","Mexico","America/Mexico_City"),("Tlalnepantla","Mexico","America/Mexico_City"),
    ("Culiacán","Mexico","America/Mazatlan"),("Hermosillo","Mexico","America/Hermosillo"),
    ("Acapulco","Mexico","America/Mexico_City"),("Naucalpan","Mexico","America/Mexico_City"),
    ("Mexicali","Mexico","America/Tijuana"),("Oaxaca","Mexico","America/Mexico_City"),
    ("Cancún","Mexico","America/Cancun"),("Querétaro","Mexico","America/Mexico_City"),
    ("Veracruz","Mexico","America/Mexico_City"),
    # Netherlands
    ("Amsterdam","Netherlands","Europe/Amsterdam"),("Rotterdam","Netherlands","Europe/Amsterdam"),
    ("The Hague","Netherlands","Europe/Amsterdam"),("Utrecht","Netherlands","Europe/Amsterdam"),
    ("Eindhoven","Netherlands","Europe/Amsterdam"),("Tilburg","Netherlands","Europe/Amsterdam"),
    ("Groningen","Netherlands","Europe/Amsterdam"),("Almere","Netherlands","Europe/Amsterdam"),
    ("Breda","Netherlands","Europe/Amsterdam"),("Nijmegen","Netherlands","Europe/Amsterdam"),
    # New Zealand
    ("Auckland","New Zealand","Pacific/Auckland"),("Wellington","New Zealand","Pacific/Auckland"),
    ("Christchurch","New Zealand","Pacific/Auckland"),("Hamilton","New Zealand","Pacific/Auckland"),
    ("Tauranga","New Zealand","Pacific/Auckland"),("Dunedin","New Zealand","Pacific/Auckland"),
    # Norway
    ("Bergen","Norway","Europe/Oslo"),("Oslo","Norway","Europe/Oslo"),
    ("Stavanger","Norway","Europe/Oslo"),("Trondheim","Norway","Europe/Oslo"),
    # Poland
    ("Warsaw","Poland","Europe/Warsaw"),("Kraków","Poland","Europe/Warsaw"),
    ("Łódź","Poland","Europe/Warsaw"),("Wrocław","Poland","Europe/Warsaw"),
    ("Poznań","Poland","Europe/Warsaw"),("Gdańsk","Poland","Europe/Warsaw"),
    ("Szczecin","Poland","Europe/Warsaw"),("Bydgoszcz","Poland","Europe/Warsaw"),
    ("Lublin","Poland","Europe/Warsaw"),("Katowice","Poland","Europe/Warsaw"),
    ("Białystok","Poland","Europe/Warsaw"),("Gdynia","Poland","Europe/Warsaw"),
    ("Częstochowa","Poland","Europe/Warsaw"),("Sosnowiec","Poland","Europe/Warsaw"),
    ("Radom","Poland","Europe/Warsaw"),("Toruń","Poland","Europe/Warsaw"),
    # Portugal
    ("Lisbon","Portugal","Europe/Lisbon"),("Porto","Portugal","Europe/Lisbon"),
    ("Amadora","Portugal","Europe/Lisbon"),("Braga","Portugal","Europe/Lisbon"),
    ("Coimbra","Portugal","Europe/Lisbon"),("Setúbal","Portugal","Europe/Lisbon"),
    # Slovakia
    ("Bratislava","Slovakia","Europe/Bratislava"),("Košice","Slovakia","Europe/Bratislava"),
    # Slovenia
    ("Ljubljana","Slovenia","Europe/Ljubljana"),
    # Spain
    ("Madrid","Spain","Europe/Madrid"),("Barcelona","Spain","Europe/Madrid"),
    ("Valencia","Spain","Europe/Madrid"),("Seville","Spain","Europe/Madrid"),
    ("Zaragoza","Spain","Europe/Madrid"),("Málaga","Spain","Europe/Madrid"),
    ("Murcia","Spain","Europe/Madrid"),("Palma","Spain","Europe/Madrid"),
    ("Las Palmas","Spain","Atlantic/Canary"),("Bilbao","Spain","Europe/Madrid"),
    ("Alicante","Spain","Europe/Madrid"),("Córdoba","Spain","Europe/Madrid"),
    ("Valladolid","Spain","Europe/Madrid"),("Vigo","Spain","Europe/Madrid"),
    ("Gijón","Spain","Europe/Madrid"),("Hospitalet de Llobregat","Spain","Europe/Madrid"),
    ("A Coruña","Spain","Europe/Madrid"),("Vitoria-Gasteiz","Spain","Europe/Madrid"),
    ("Granada","Spain","Europe/Madrid"),("Elche","Spain","Europe/Madrid"),
    ("Oviedo","Spain","Europe/Madrid"),("Santa Cruz de Tenerife","Spain","Atlantic/Canary"),
    ("Badalona","Spain","Europe/Madrid"),("Cartagena","Spain","Europe/Madrid"),
    ("Sabadell","Spain","Europe/Madrid"),("Jerez de la Frontera","Spain","Europe/Madrid"),
    ("Móstoles","Spain","Europe/Madrid"),("Alcalá de Henares","Spain","Europe/Madrid"),
    ("Pamplona","Spain","Europe/Madrid"),("Fuenlabrada","Spain","Europe/Madrid"),
    # Sweden
    ("Stockholm","Sweden","Europe/Stockholm"),("Gothenburg","Sweden","Europe/Stockholm"),
    ("Malmö","Sweden","Europe/Stockholm"),("Uppsala","Sweden","Europe/Stockholm"),
    ("Västerås","Sweden","Europe/Stockholm"),
    # Switzerland
    ("Zurich","Switzerland","Europe/Zurich"),("Geneva","Switzerland","Europe/Zurich"),
    ("Basel","Switzerland","Europe/Zurich"),("Bern","Switzerland","Europe/Zurich"),
    ("Lausanne","Switzerland","Europe/Zurich"),
    # Turkey
    ("Istanbul","Turkey","Europe/Istanbul"),("Ankara","Turkey","Europe/Istanbul"),
    ("Izmir","Turkey","Europe/Istanbul"),("Bursa","Turkey","Europe/Istanbul"),
    ("Antalya","Turkey","Europe/Istanbul"),("Adana","Turkey","Europe/Istanbul"),
    ("Gaziantep","Turkey","Europe/Istanbul"),("Konya","Turkey","Europe/Istanbul"),
    ("Şanlıurfa","Turkey","Europe/Istanbul"),("Mersin","Turkey","Europe/Istanbul"),
    ("Kayseri","Turkey","Europe/Istanbul"),("Eskişehir","Turkey","Europe/Istanbul"),
    ("Diyarbakır","Turkey","Europe/Istanbul"),("Denizli","Turkey","Europe/Istanbul"),
    ("Samsun","Turkey","Europe/Istanbul"),("Trabzon","Turkey","Europe/Istanbul"),
    # United Kingdom
    ("London","United Kingdom","Europe/London"),("Birmingham","United Kingdom","Europe/London"),
    ("Leeds","United Kingdom","Europe/London"),("Glasgow","United Kingdom","Europe/London"),
    ("Manchester","United Kingdom","Europe/London"),("Sheffield","United Kingdom","Europe/London"),
    ("Bradford","United Kingdom","Europe/London"),("Edinburgh","United Kingdom","Europe/London"),
    ("Liverpool","United Kingdom","Europe/London"),("Bristol","United Kingdom","Europe/London"),
    ("Cardiff","United Kingdom","Europe/London"),("Coventry","United Kingdom","Europe/London"),
    ("Nottingham","United Kingdom","Europe/London"),("Leicester","United Kingdom","Europe/London"),
    ("Sunderland","United Kingdom","Europe/London"),("Belfast","United Kingdom","Europe/London"),
    ("Newcastle upon Tyne","United Kingdom","Europe/London"),("Brighton","United Kingdom","Europe/London"),
    ("Hull","United Kingdom","Europe/London"),("Plymouth","United Kingdom","Europe/London"),
    ("Stoke-on-Trent","United Kingdom","Europe/London"),("Wolverhampton","United Kingdom","Europe/London"),
    ("Derby","United Kingdom","Europe/London"),("Southampton","United Kingdom","Europe/London"),
    ("Oxford","United Kingdom","Europe/London"),("Cambridge","United Kingdom","Europe/London"),
    # United States
    ("New York City","United States","America/New_York"),
    ("Los Angeles","United States","America/Los_Angeles"),
    ("Chicago","United States","America/Chicago"),
    ("Houston","United States","America/Chicago"),
    ("Phoenix","United States","America/Phoenix"),
    ("Philadelphia","United States","America/New_York"),
    ("San Antonio","United States","America/Chicago"),
    ("San Diego","United States","America/Los_Angeles"),
    ("Dallas","United States","America/Chicago"),
    ("San Jose","United States","America/Los_Angeles"),
    ("Austin","United States","America/Chicago"),
    ("Jacksonville","United States","America/New_York"),
    ("Fort Worth","United States","America/Chicago"),
    ("Columbus","United States","America/New_York"),
    ("Charlotte","United States","America/New_York"),
    ("Indianapolis","United States","America/Indiana/Indianapolis"),
    ("San Francisco","United States","America/Los_Angeles"),
    ("Seattle","United States","America/Los_Angeles"),
    ("Denver","United States","America/Denver"),
    ("Washington DC","United States","America/New_York"),
    ("Nashville","United States","America/Chicago"),
    ("Oklahoma City","United States","America/Chicago"),
    ("El Paso","United States","America/Denver"),
    ("Boston","United States","America/New_York"),
    ("Portland","United States","America/Los_Angeles"),
    ("Las Vegas","United States","America/Los_Angeles"),
    ("Memphis","United States","America/Chicago"),
    ("Louisville","United States","America/Kentucky/Louisville"),
    ("Baltimore","United States","America/New_York"),
    ("Milwaukee","United States","America/Chicago"),
    ("Albuquerque","United States","America/Denver"),
    ("Tucson","United States","America/Phoenix"),
    ("Fresno","United States","America/Los_Angeles"),
    ("Sacramento","United States","America/Los_Angeles"),
    ("Kansas City","United States","America/Chicago"),
    ("Atlanta","United States","America/New_York"),
    ("Long Beach","United States","America/Los_Angeles"),
    ("Mesa","United States","America/Phoenix"),
    ("Omaha","United States","America/Chicago"),
    ("Raleigh","United States","America/New_York"),
    ("Cleveland","United States","America/New_York"),
    ("Virginia Beach","United States","America/New_York"),
    ("Colorado Springs","United States","America/Denver"),
    ("Tulsa","United States","America/Chicago"),
    ("Oakland","United States","America/Los_Angeles"),
    ("Minneapolis","United States","America/Chicago"),
    ("Tampa","United States","America/New_York"),
    ("New Orleans","United States","America/Chicago"),
    ("Wichita","United States","America/Chicago"),
    ("Arlington","United States","America/Chicago"),
    ("Bakersfield","United States","America/Los_Angeles"),
    ("Aurora","United States","America/Denver"),
    ("Anaheim","United States","America/Los_Angeles"),
    ("Santa Ana","United States","America/Los_Angeles"),
    ("Corpus Christi","United States","America/Chicago"),
    ("Riverside","United States","America/Los_Angeles"),
    ("St. Louis","United States","America/Chicago"),
    ("Lexington","United States","America/New_York"),
    ("Pittsburgh","United States","America/New_York"),
    ("Anchorage","United States","America/Anchorage"),
    ("Stockton","United States","America/Los_Angeles"),
    ("Cincinnati","United States","America/New_York"),
    ("St. Paul","United States","America/Chicago"),
    ("Greensboro","United States","America/New_York"),
    ("Toledo","United States","America/New_York"),
    ("Newark","United States","America/New_York"),
    ("Plano","United States","America/Chicago"),
    ("Henderson","United States","America/Los_Angeles"),
    ("Orlando","United States","America/New_York"),
    ("Lincoln","United States","America/Chicago"),
    ("Jersey City","United States","America/New_York"),
    ("Chandler","United States","America/Phoenix"),
    ("St. Petersburg","United States","America/New_York"),
    ("Laredo","United States","America/Chicago"),
    ("Norfolk","United States","America/New_York"),
    ("Madison","United States","America/Chicago"),
    ("Durham","United States","America/New_York"),
    ("Lubbock","United States","America/Chicago"),
    ("Winston-Salem","United States","America/New_York"),
    ("Garland","United States","America/Chicago"),
    ("Glendale","United States","America/Los_Angeles"),
    ("Hialeah","United States","America/New_York"),
    ("Reno","United States","America/Los_Angeles"),
    ("Baton Rouge","United States","America/Chicago"),
    ("Irvine","United States","America/Los_Angeles"),
    ("Chesapeake","United States","America/New_York"),
    ("Irving","United States","America/Chicago"),
    ("Scottsdale","United States","America/Phoenix"),
    ("North Las Vegas","United States","America/Los_Angeles"),
    ("Fremont","United States","America/Los_Angeles"),
    ("Gilbert","United States","America/Phoenix"),
    ("San Bernardino","United States","America/Los_Angeles"),
    ("Birmingham","United States","America/Chicago"),
    ("Rochester","United States","America/New_York"),
    ("Richmond","United States","America/New_York"),
    ("Spokane","United States","America/Los_Angeles"),
    ("Des Moines","United States","America/Chicago"),
    ("Montgomery","United States","America/Chicago"),
    ("Modesto","United States","America/Los_Angeles"),
    ("Tacoma","United States","America/Los_Angeles"),
    ("Fontana","United States","America/Los_Angeles"),
    ("Columbus","United States","America/Chicago"),
    ("Fayetteville","United States","America/Chicago"),
    ("Moreno Valley","United States","America/Los_Angeles"),
    ("Akron","United States","America/New_York"),
    ("Yonkers","United States","America/New_York"),
    ("Glendale","United States","America/Phoenix"),
    ("Huntington Beach","United States","America/Los_Angeles"),
    ("Little Rock","United States","America/Chicago"),
    ("Salt Lake City","United States","America/Denver"),
    ("Grand Rapids","United States","America/New_York"),
    ("Tallahassee","United States","America/New_York"),
    ("Huntsville","United States","America/Chicago"),
    ("Worcester","United States","America/New_York"),
    ("Knoxville","United States","America/New_York"),
    ("Providence","United States","America/New_York"),
    ("Miami","United States","America/New_York"),
    ("Fort Lauderdale","United States","America/New_York"),
    ("Honolulu","United States","Pacific/Honolulu"),
    ("Detroit","United States","America/New_York"),
    ("El Monte","United States","America/Los_Angeles"),
    ("Brownsville","United States","America/Chicago"),
    ("Peoria","United States","America/Chicago"),
    ("Santa Clarita","United States","America/Los_Angeles"),
    ("Augusta","United States","America/New_York"),
    ("Tempe","United States","America/Phoenix"),
    ("Cape Coral","United States","America/New_York"),
    ("Overland Park","United States","America/Chicago"),
    ("Oceanside","United States","America/Los_Angeles"),
    ("Garden Grove","United States","America/Los_Angeles"),
    ("Vancouver","United States","America/Los_Angeles"),
    ("Chattanooga","United States","America/New_York"),
    ("Fort Collins","United States","America/Denver"),
    ("Jackson","United States","America/Chicago"),
    ("Eugene","United States","America/Los_Angeles"),
    ("Shreveport","United States","America/Chicago"),
    ("Ontario","United States","America/Los_Angeles"),
    ("Corona","United States","America/Los_Angeles"),
    ("Elk Grove","United States","America/Los_Angeles"),
    ("Flint","United States","America/New_York"),
    ("Springfield","United States","America/Chicago"),
    ("Clarksville","United States","America/Chicago"),
    ("Salinas","United States","America/Los_Angeles"),
    ("Lakewood","United States","America/Denver"),
    ("Palmdale","United States","America/Los_Angeles"),
    ("Sunnyvale","United States","America/Los_Angeles"),
    ("Pomona","United States","America/Los_Angeles"),
    ("Escondido","United States","America/Los_Angeles"),
    ("Kansas City","United States","America/Chicago"),
    ("Savannah","United States","America/New_York"),
    ("Paterson","United States","America/New_York"),
    ("Torrance","United States","America/Los_Angeles"),
    ("Hayward","United States","America/Los_Angeles"),
    ("Alexandria","United States","America/New_York"),
    ("Rockford","United States","America/Chicago"),
    ("Sunnyvale","United States","America/Los_Angeles"),
    ("Pasadena","United States","America/Los_Angeles"),
    ("Mesquite","United States","America/Chicago"),
]

def run():
    db = SessionLocal()
    added = 0
    skipped = 0
    try:
        existing = {(c.name, c.country) for c in db.query(City).all()}
        seen = set()
        for name, country, timezone in CITIES:
            key = (name, country)
            if key in existing or key in seen:
                skipped += 1
                continue
            seen.add(key)
            db.add(City(name=name, country=country, timezone=timezone))
            added += 1
        db.commit()
        print(f"Done — added: {added}, skipped (already exist): {skipped}")
    finally:
        db.close()

if __name__ == "__main__":
    run()
