"""Seed all 1,317 OECD cities. Run: python3 scripts/seed_cities_full.py"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app.database import SessionLocal
from app.models import City
CITIES = [
  ("Adelaide", "Australia", "Australia/Adelaide"),
  ("Bendigo", "Australia", "Australia/Melbourne"),
  ("Brisbane", "Australia", "Australia/Brisbane"),
  ("Cairns", "Australia", "Australia/Brisbane"),
  ("Canberra", "Australia", "Australia/Sydney"),
  ("Darwin", "Australia", "Australia/Darwin"),
  ("Geelong", "Australia", "Australia/Melbourne"),
  ("Gold Coast", "Australia", "Australia/Brisbane"),
  ("Hobart", "Australia", "Australia/Hobart"),
  ("Launceston", "Australia", "Australia/Hobart"),
  ("Logan City", "Australia", "Australia/Brisbane"),
  ("Melbourne", "Australia", "Australia/Melbourne"),
  ("Newcastle", "Australia", "Australia/Sydney"),
  ("Perth", "Australia", "Australia/Perth"),
  ("Sydney", "Australia", "Australia/Sydney"),
  ("Toowoomba", "Australia", "Australia/Brisbane"),
  ("Townsville", "Australia", "Australia/Brisbane"),
  ("Graz", "Austria", "Europe/Vienna"),
  ("Innsbruck", "Austria", "Europe/Vienna"),
  ("Linz", "Austria", "Europe/Vienna"),
  ("Salzburg", "Austria", "Europe/Vienna"),
  ("Vienna", "Austria", "Europe/Vienna"),
  ("Antwerpen", "Belgium", "Europe/Brussels"),
  ("Brugge", "Belgium", "Europe/Brussels"),
  ("Brussels", "Belgium", "Europe/Brussels"),
  ("Charleroi", "Belgium", "Europe/Brussels"),
  ("Gent", "Belgium", "Europe/Brussels"),
  ("Liège", "Belgium", "Europe/Brussels"),
  ("Namur", "Belgium", "Europe/Brussels"),
  ("Abbotsford", "Canada", "America/Vancouver"),
  ("Anmore", "Canada", "America/Vancouver"),
  ("Barrie", "Canada", "America/Toronto"),
  ("Brampton", "Canada", "America/Toronto"),
  ("Burlington", "Canada", "America/Toronto"),
  ("Burnaby", "Canada", "America/Vancouver"),
  ("Calgary", "Canada", "America/Edmonton"),
  ("Cambridge", "Canada", "America/Toronto"),
  ("Coquitlam", "Canada", "America/Vancouver"),
  ("Dartmouth", "Canada", "America/Halifax"),
  ("Delta", "Canada", "America/Vancouver"),
  ("East York", "Canada", "America/Toronto"),
  ("Edmonton", "Canada", "America/Edmonton"),
  ("Etobicoke", "Canada", "America/Toronto"),
  ("Gatineau", "Canada", "America/Toronto"),
  ("Greater Sudbury", "Canada", "America/Toronto"),
  ("Guelph", "Canada", "America/Toronto"),
  ("Halifax", "Canada", "America/Halifax"),
  ("Hamilton", "Canada", "America/Toronto"),
  ("Kelowna", "Canada", "America/Vancouver"),
  ("Kingston", "Canada", "America/Toronto"),
  ("Kitchener", "Canada", "America/Toronto"),
  ("Ladner", "Canada", "America/Vancouver"),
  ("Laval", "Canada", "America/Toronto"),
  ("London", "Canada", "America/Toronto"),
  ("Longueuil", "Canada", "America/Toronto"),
  ("Lévis", "Canada", "America/Blanc-Sablon"),
  ("Markham", "Canada", "America/Toronto"),
  ("Mississauga", "Canada", "America/Toronto"),
  ("Montréal", "Canada", "America/Toronto"),
  ("North York", "Canada", "America/Toronto"),
  ("Oakville", "Canada", "America/Toronto"),
  ("Oshawa", "Canada", "America/Toronto"),
  ("Ottawa", "Canada", "America/Toronto"),
  ("Québec", "Canada", "America/Toronto"),
  ("Regina", "Canada", "America/Regina"),
  ("Richmond", "Canada", "America/Vancouver"),
  ("Richmond Hill", "Canada", "America/Toronto"),
  ("Saguenay", "Canada", "America/Toronto"),
  ("Saskatoon", "Canada", "America/Regina"),
  ("Scarborough", "Canada", "America/Toronto"),
  ("Sherbrooke", "Canada", "America/Toronto"),
  ("St. Catharines", "Canada", "America/Toronto"),
  ("Surrey", "Canada", "America/Vancouver"),
  ("Sydney", "Canada", "America/Glace_Bay"),
  ("Toronto", "Canada", "America/Toronto"),
  ("Trois-Rivières", "Canada", "America/Toronto"),
  ("Vancouver", "Canada", "America/Vancouver"),
  ("Vaughan", "Canada", "America/Toronto"),
  ("Victoria", "Canada", "America/Vancouver"),
  ("Windsor", "Canada", "America/Toronto"),
  ("Winnipeg", "Canada", "America/Winnipeg"),
  ("Antofagasta", "Chile", "America/Santiago"),
  ("Arica", "Chile", "America/Santiago"),
  ("Calama", "Chile", "America/Santiago"),
  ("Chillán", "Chile", "America/Santiago"),
  ("Concepción", "Chile", "America/Santiago"),
  ("Copiapó", "Chile", "America/Santiago"),
  ("Coquimbo", "Chile", "America/Santiago"),
  ("Curicó", "Chile", "America/Santiago"),
  ("Iquique", "Chile", "America/Santiago"),
  ("La Pintana", "Chile", "America/Santiago"),
  ("La Serena", "Chile", "America/Santiago"),
  ("Lo Prado", "Chile", "America/Santiago"),
  ("Los Ángeles", "Chile", "America/Santiago"),
  ("Osorno", "Chile", "America/Santiago"),
  ("Puente Alto", "Chile", "America/Santiago"),
  ("Puerto Montt", "Chile", "America/Santiago"),
  ("Punta Arenas", "Chile", "America/Santiago"),
  ("Quilpué", "Chile", "America/Santiago"),
  ("Rancagua", "Chile", "America/Santiago"),
  ("San Bernardo", "Chile", "America/Santiago"),
  ("Santiago", "Chile", "America/Santiago"),
  ("Talca", "Chile", "America/Santiago"),
  ("Talcahuano", "Chile", "America/Santiago"),
  ("Temuco", "Chile", "America/Santiago"),
  ("Valdivia", "Chile", "America/Santiago"),
  ("Valparaíso", "Chile", "America/Santiago"),
  ("Viña del Mar", "Chile", "America/Santiago"),
  ("Armenia", "Colombia", "America/Bogota"),
  ("Barrancabermeja", "Colombia", "America/Bogota"),
  ("Barranquilla", "Colombia", "America/Bogota"),
  ("Bello", "Colombia", "America/Bogota"),
  ("Bogotá", "Colombia", "America/Bogota"),
  ("Bucaramanga", "Colombia", "America/Bogota"),
  ("Buenaventura", "Colombia", "America/Bogota"),
  ("Buga", "Colombia", "America/Bogota"),
  ("Cali", "Colombia", "America/Bogota"),
  ("Cartagena", "Colombia", "America/Bogota"),
  ("Cartago", "Colombia", "America/Bogota"),
  ("Cúcuta", "Colombia", "America/Bogota"),
  ("Dos Quebradas", "Colombia", "America/Bogota"),
  ("Envigado", "Colombia", "America/Bogota"),
  ("Florencia", "Colombia", "America/Bogota"),
  ("Floridablanca", "Colombia", "America/Bogota"),
  ("Girardot City", "Colombia", "America/Bogota"),
  ("Girón", "Colombia", "America/Bogota"),
  ("Ibagué", "Colombia", "America/Bogota"),
  ("Itagüí", "Colombia", "America/Bogota"),
  ("Magangué", "Colombia", "America/Bogota"),
  ("Maicao", "Colombia", "America/Bogota"),
  ("Malambo", "Colombia", "America/Bogota"),
  ("Manizales", "Colombia", "America/Bogota"),
  ("Medellín", "Colombia", "America/Bogota"),
  ("Montería", "Colombia", "America/Bogota"),
  ("Neiva", "Colombia", "America/Bogota"),
  ("Palmira", "Colombia", "America/Bogota"),
  ("Pasto", "Colombia", "America/Bogota"),
  ("Pereira", "Colombia", "America/Bogota"),
  ("Popayán", "Colombia", "America/Bogota"),
  ("Santa Marta", "Colombia", "America/Bogota"),
  ("Sincelejo", "Colombia", "America/Bogota"),
  ("Soacha", "Colombia", "America/Bogota"),
  ("Sogamoso", "Colombia", "America/Bogota"),
  ("Soledad", "Colombia", "America/Bogota"),
  ("Tuluá", "Colombia", "America/Bogota"),
  ("Tunja", "Colombia", "America/Bogota"),
  ("Valledupar", "Colombia", "America/Bogota"),
  ("Villavicencio", "Colombia", "America/Bogota"),
  ("San José", "Costa Rica", "America/Costa_Rica"),
  ("Brno", "Czechia", "Europe/Prague"),
  ("Olomouc", "Czechia", "Europe/Prague"),
  ("Ostrava", "Czechia", "Europe/Prague"),
  ("Pilsen", "Czechia", "Europe/Prague"),
  ("Prague", "Czechia", "Europe/Prague"),
  ("Aalborg", "Denmark", "Europe/Copenhagen"),
  ("Copenhagen", "Denmark", "Europe/Copenhagen"),
  ("Odense", "Denmark", "Europe/Copenhagen"),
  ("Århus", "Denmark", "Europe/Copenhagen"),
  ("Tallinn", "Estonia", "Europe/Tallinn"),
  ("Tartu", "Estonia", "Europe/Tallinn"),
  ("Espoo", "Finland", "Europe/Helsinki"),
  ("Helsinki", "Finland", "Europe/Helsinki"),
  ("Oulu", "Finland", "Europe/Helsinki"),
  ("Tampere", "Finland", "Europe/Helsinki"),
  ("Turku", "Finland", "Europe/Helsinki"),
  ("Vantaa", "Finland", "Europe/Helsinki"),
  ("Aix-en-Provence", "France", "Europe/Paris"),
  ("Amiens", "France", "Europe/Paris"),
  ("Angers", "France", "Europe/Paris"),
  ("Argenteuil", "France", "Europe/Paris"),
  ("Besançon", "France", "Europe/Paris"),
  ("Bordeaux", "France", "Europe/Paris"),
  ("Boulogne-Billancourt", "France", "Europe/Paris"),
  ("Brest", "France", "Europe/Paris"),
  ("Caen", "France", "Europe/Paris"),
  ("Clermont-Ferrand", "France", "Europe/Paris"),
  ("Dijon", "France", "Europe/Paris"),
  ("Grenoble", "France", "Europe/Paris"),
  ("Le Havre", "France", "Europe/Paris"),
  ("Le Mans", "France", "Europe/Paris"),
  ("Lille", "France", "Europe/Paris"),
  ("Limoges", "France", "Europe/Paris"),
  ("Lyon", "France", "Europe/Paris"),
  ("Marseille", "France", "Europe/Paris"),
  ("Metz", "France", "Europe/Paris"),
  ("Montpellier", "France", "Europe/Paris"),
  ("Mulhouse", "France", "Europe/Paris"),
  ("Nancy", "France", "Europe/Paris"),
  ("Nantes", "France", "Europe/Paris"),
  ("Nice", "France", "Europe/Paris"),
  ("Nîmes", "France", "Europe/Paris"),
  ("Orléans", "France", "Europe/Paris"),
  ("Paris", "France", "Europe/Paris"),
  ("Perpignan", "France", "Europe/Paris"),
  ("Reims", "France", "Europe/Paris"),
  ("Rennes", "France", "Europe/Paris"),
  ("Rouen", "France", "Europe/Paris"),
  ("Saint-Quentin-en-Yvelines", "France", "Europe/Paris"),
  ("Saint-Étienne", "France", "Europe/Paris"),
  ("Strasbourg", "France", "Europe/Paris"),
  ("Toulon", "France", "Europe/Paris"),
  ("Toulouse", "France", "Europe/Paris"),
  ("Tours", "France", "Europe/Paris"),
  ("Villeurbanne", "France", "Europe/Paris"),
  ("Aachen", "Germany", "Europe/Berlin"),
  ("Augsburg", "Germany", "Europe/Berlin"),
  ("Bergisch Gladbach", "Germany", "Europe/Berlin"),
  ("Berlin", "Germany", "Europe/Berlin"),
  ("Bielefeld", "Germany", "Europe/Berlin"),
  ("Bochum", "Germany", "Europe/Berlin"),
  ("Bonn", "Germany", "Europe/Berlin"),
  ("Bottrop", "Germany", "Europe/Berlin"),
  ("Braunschweig", "Germany", "Europe/Berlin"),
  ("Bremen", "Germany", "Europe/Berlin"),
  ("Bremerhaven", "Germany", "Europe/Berlin"),
  ("Chemnitz", "Germany", "Europe/Berlin"),
  ("Darmstadt", "Germany", "Europe/Berlin"),
  ("Dortmund", "Germany", "Europe/Berlin"),
  ("Dresden", "Germany", "Europe/Berlin"),
  ("Duisburg", "Germany", "Europe/Berlin"),
  ("Düsseldorf", "Germany", "Europe/Berlin"),
  ("Erfurt", "Germany", "Europe/Berlin"),
  ("Erlangen", "Germany", "Europe/Berlin"),
  ("Essen", "Germany", "Europe/Berlin"),
  ("Frankfurt am Main", "Germany", "Europe/Berlin"),
  ("Freiburg", "Germany", "Europe/Berlin"),
  ("Fürth", "Germany", "Europe/Berlin"),
  ("Gelsenkirchen", "Germany", "Europe/Berlin"),
  ("Gera", "Germany", "Europe/Berlin"),
  ("Göttingen", "Germany", "Europe/Berlin"),
  ("Hagen", "Germany", "Europe/Berlin"),
  ("Halle (Saale)", "Germany", "Europe/Berlin"),
  ("Hamburg", "Germany", "Europe/Berlin"),
  ("Hamm", "Germany", "Europe/Berlin"),
  ("Hannover", "Germany", "Europe/Berlin"),
  ("Heidelberg", "Germany", "Europe/Berlin"),
  ("Heilbronn", "Germany", "Europe/Berlin"),
  ("Herne", "Germany", "Europe/Berlin"),
  ("Hildesheim", "Germany", "Europe/Berlin"),
  ("Ingolstadt", "Germany", "Europe/Berlin"),
  ("Jena", "Germany", "Europe/Berlin"),
  ("Karlsruhe", "Germany", "Europe/Berlin"),
  ("Kassel", "Germany", "Europe/Berlin"),
  ("Kiel", "Germany", "Europe/Berlin"),
  ("Koblenz", "Germany", "Europe/Berlin"),
  ("Krefeld", "Germany", "Europe/Berlin"),
  ("Köln", "Germany", "Europe/Berlin"),
  ("Leipzig", "Germany", "Europe/Berlin"),
  ("Leverkusen", "Germany", "Europe/Berlin"),
  ("Ludwigshafen am Rhein", "Germany", "Europe/Berlin"),
  ("Lübeck", "Germany", "Europe/Berlin"),
  ("Magdeburg", "Germany", "Europe/Berlin"),
  ("Mainz", "Germany", "Europe/Berlin"),
  ("Mannheim", "Germany", "Europe/Berlin"),
  ("Moers", "Germany", "Europe/Berlin"),
  ("Munich", "Germany", "Europe/Berlin"),
  ("Mönchengladbach", "Germany", "Europe/Berlin"),
  ("Mülheim", "Germany", "Europe/Berlin"),
  ("Münster", "Germany", "Europe/Berlin"),
  ("Neuss", "Germany", "Europe/Berlin"),
  ("Nürnberg", "Germany", "Europe/Berlin"),
  ("Oberhausen", "Germany", "Europe/Berlin"),
  ("Offenbach", "Germany", "Europe/Berlin"),
  ("Oldenburg", "Germany", "Europe/Berlin"),
  ("Osnabrück", "Germany", "Europe/Berlin"),
  ("Paderborn", "Germany", "Europe/Berlin"),
  ("Pforzheim", "Germany", "Europe/Berlin"),
  ("Potsdam", "Germany", "Europe/Berlin"),
  ("Recklinghausen", "Germany", "Europe/Berlin"),
  ("Regensburg", "Germany", "Europe/Berlin"),
  ("Remscheid", "Germany", "Europe/Berlin"),
  ("Reutlingen", "Germany", "Europe/Berlin"),
  ("Rostock", "Germany", "Europe/Berlin"),
  ("Saarbrücken", "Germany", "Europe/Berlin"),
  ("Siegen", "Germany", "Europe/Berlin"),
  ("Solingen", "Germany", "Europe/Berlin"),
  ("Stuttgart", "Germany", "Europe/Berlin"),
  ("Trier", "Germany", "Europe/Berlin"),
  ("Ulm", "Germany", "Europe/Berlin"),
  ("Wiesbaden", "Germany", "Europe/Berlin"),
  ("Witten", "Germany", "Europe/Berlin"),
  ("Wolfsburg", "Germany", "Europe/Berlin"),
  ("Wuppertal", "Germany", "Europe/Berlin"),
  ("Würzburg", "Germany", "Europe/Berlin"),
  ("Athens", "Greece", "Europe/Athens"),
  ("Irákleion", "Greece", "Europe/Athens"),
  ("Kallithéa", "Greece", "Europe/Athens"),
  ("Lárisa", "Greece", "Europe/Athens"),
  ("Peristéri", "Greece", "Europe/Athens"),
  ("Piraeus", "Greece", "Europe/Athens"),
  ("Pátra", "Greece", "Europe/Athens"),
  ("Thessaloníki", "Greece", "Europe/Athens"),
  ("Budapest", "Hungary", "Europe/Budapest"),
  ("Debrecen", "Hungary", "Europe/Budapest"),
  ("Győr", "Hungary", "Europe/Budapest"),
  ("Kecskemét", "Hungary", "Europe/Budapest"),
  ("Miskolc", "Hungary", "Europe/Budapest"),
  ("Nyíregyháza", "Hungary", "Europe/Budapest"),
  ("Pécs", "Hungary", "Europe/Budapest"),
  ("Szeged", "Hungary", "Europe/Budapest"),
  ("Székesfehérvár", "Hungary", "Europe/Budapest"),
  ("Reykjavík", "Iceland", "Atlantic/Reykjavik"),
  ("Cork", "Ireland", "Europe/Dublin"),
  ("Dublin", "Ireland", "Europe/Dublin"),
  ("Dún Laoghaire", "Ireland", "Europe/Dublin"),
  ("Ashdod", "Israel", "Asia/Jerusalem"),
  ("Ashqelon", "Israel", "Asia/Jerusalem"),
  ("Bat Yam", "Israel", "Asia/Jerusalem"),
  ("Beersheba", "Israel", "Asia/Jerusalem"),
  ("Bené Beraq", "Israel", "Asia/Jerusalem"),
  ("Haifa", "Israel", "Asia/Jerusalem"),
  ("H̱olon", "Israel", "Asia/Jerusalem"),
  ("Jerusalem", "Israel", "Asia/Jerusalem"),
  ("Netanya", "Israel", "Asia/Jerusalem"),
  ("Petaẖ Tiqwa", "Israel", "Asia/Jerusalem"),
  ("Ramat Gan", "Israel", "Asia/Jerusalem"),
  ("Rishon LeẔiyyon", "Israel", "Asia/Jerusalem"),
  ("Tel Aviv", "Israel", "Asia/Jerusalem"),
  ("Acilia-Castel Fusano-Ostia Antica", "Italy", "Europe/Rome"),
  ("Bari", "Italy", "Europe/Rome"),
  ("Bergamo", "Italy", "Europe/Rome"),
  ("Bologna", "Italy", "Europe/Rome"),
  ("Brescia", "Italy", "Europe/Rome"),
  ("Cagliari", "Italy", "Europe/Rome"),
  ("Catania", "Italy", "Europe/Rome"),
  ("Florence", "Italy", "Europe/Rome"),
  ("Foggia", "Italy", "Europe/Rome"),
  ("Genoa", "Italy", "Europe/Rome"),
  ("Livorno", "Italy", "Europe/Rome"),
  ("Messina", "Italy", "Europe/Rome"),
  ("Mestre", "Italy", "Europe/Rome"),
  ("Milan", "Italy", "Europe/Rome"),
  ("Modena", "Italy", "Europe/Rome"),
  ("Monza", "Italy", "Europe/Rome"),
  ("Naples", "Italy", "Europe/Rome"),
  ("Padova", "Italy", "Europe/Rome"),
  ("Palermo", "Italy", "Europe/Rome"),
  ("Parma", "Italy", "Europe/Rome"),
  ("Perugia", "Italy", "Europe/Rome"),
  ("Pescara", "Italy", "Europe/Rome"),
  ("Prato", "Italy", "Europe/Rome"),
  ("Reggio Calabria", "Italy", "Europe/Rome"),
  ("Reggio nell'Emilia", "Italy", "Europe/Rome"),
  ("Rimini", "Italy", "Europe/Rome"),
  ("Rome", "Italy", "Europe/Rome"),
  ("Salerno", "Italy", "Europe/Rome"),
  ("Taranto", "Italy", "Europe/Rome"),
  ("Trieste", "Italy", "Europe/Rome"),
  ("Turin", "Italy", "Europe/Rome"),
  ("Verona", "Italy", "Europe/Rome"),
  ("Vicenza", "Italy", "Europe/Rome"),
  ("Abiko", "Japan", "Asia/Tokyo"),
  ("Ageoshimo", "Japan", "Asia/Tokyo"),
  ("Akashi", "Japan", "Asia/Tokyo"),
  ("Akita", "Japan", "Asia/Tokyo"),
  ("Akita", "Japan", "Asia/Tokyo"),
  ("Amagasaki", "Japan", "Asia/Tokyo"),
  ("Anjō", "Japan", "Asia/Tokyo"),
  ("Aomorishi", "Japan", "Asia/Tokyo"),
  ("Asahikawa", "Japan", "Asia/Tokyo"),
  ("Asaka", "Japan", "Asia/Tokyo"),
  ("Ashikaga", "Japan", "Asia/Tokyo"),
  ("Atsugi", "Japan", "Asia/Tokyo"),
  ("Beppu", "Japan", "Asia/Tokyo"),
  ("Chiba", "Japan", "Asia/Tokyo"),
  ("Chigasaki", "Japan", "Asia/Tokyo"),
  ("Chikushino-shi", "Japan", "Asia/Tokyo"),
  ("Daitōchō", "Japan", "Asia/Tokyo"),
  ("Ebetsu", "Japan", "Asia/Tokyo"),
  ("Fuji", "Japan", "Asia/Tokyo"),
  ("Fujieda", "Japan", "Asia/Tokyo"),
  ("Fujinomiya", "Japan", "Asia/Tokyo"),
  ("Fujisawa", "Japan", "Asia/Tokyo"),
  ("Fukui-shi", "Japan", "Asia/Tokyo"),
  ("Fukuoka", "Japan", "Asia/Tokyo"),
  ("Fukushima", "Japan", "Asia/Tokyo"),
  ("Fukuyama", "Japan", "Asia/Tokyo"),
  ("Gifu-shi", "Japan", "Asia/Tokyo"),
  ("Hachinohe", "Japan", "Asia/Tokyo"),
  ("Hachiōji", "Japan", "Asia/Tokyo"),
  ("Hadano", "Japan", "Asia/Tokyo"),
  ("Hakodate", "Japan", "Asia/Tokyo"),
  ("Hamamatsu", "Japan", "Asia/Tokyo"),
  ("Handa", "Japan", "Asia/Tokyo"),
  ("Higashimurayama-shi", "Japan", "Asia/Tokyo"),
  ("Hikone", "Japan", "Asia/Tokyo"),
  ("Himeji", "Japan", "Asia/Tokyo"),
  ("Hino", "Japan", "Asia/Tokyo"),
  ("Hirakata", "Japan", "Asia/Tokyo"),
  ("Hiratsuka", "Japan", "Asia/Tokyo"),
  ("Hirosaki", "Japan", "Asia/Tokyo"),
  ("Hiroshima", "Japan", "Asia/Tokyo"),
  ("Hitachi", "Japan", "Asia/Tokyo"),
  ("Hitachi-Naka", "Japan", "Asia/Tokyo"),
  ("Honchō", "Japan", "Asia/Tokyo"),
  ("Honmachi", "Japan", "Asia/Tokyo"),
  ("Hōfu", "Japan", "Asia/Tokyo"),
  ("Ibaraki", "Japan", "Asia/Tokyo"),
  ("Ichihara", "Japan", "Asia/Tokyo"),
  ("Ichinomiya", "Japan", "Asia/Tokyo"),
  ("Iida", "Japan", "Asia/Tokyo"),
  ("Ikoma", "Japan", "Asia/Tokyo"),
  ("Inazawa", "Japan", "Asia/Tokyo"),
  ("Isehara", "Japan", "Asia/Tokyo"),
  ("Isesaki", "Japan", "Asia/Tokyo"),
  ("Ishinomaki", "Japan", "Asia/Tokyo"),
  ("Itami", "Japan", "Asia/Tokyo"),
  ("Iwaki", "Japan", "Asia/Tokyo"),
  ("Iwakuni", "Japan", "Asia/Tokyo"),
  ("Iwatsuki", "Japan", "Asia/Tokyo"),
  ("Izumi", "Japan", "Asia/Tokyo"),
  ("Jōetsu", "Japan", "Asia/Tokyo"),
  ("Kadoma", "Japan", "Asia/Tokyo"),
  ("Kagoshima", "Japan", "Asia/Tokyo"),
  ("Kakamigahara", "Japan", "Asia/Tokyo"),
  ("Kakogawachō-honmachi", "Japan", "Asia/Tokyo"),
  ("Kamakura", "Japan", "Asia/Tokyo"),
  ("Kamirenjaku", "Japan", "Asia/Tokyo"),
  ("Kanazawa", "Japan", "Asia/Tokyo"),
  ("Kariya", "Japan", "Asia/Tokyo"),
  ("Kashihara-shi", "Japan", "Asia/Tokyo"),
  ("Kashiwa", "Japan", "Asia/Tokyo"),
  ("Kasugai", "Japan", "Asia/Tokyo"),
  ("Kasukabe", "Japan", "Asia/Tokyo"),
  ("Katsuta", "Japan", "Asia/Tokyo"),
  ("Kawagoe", "Japan", "Asia/Tokyo"),
  ("Kawaguchi", "Japan", "Asia/Tokyo"),
  ("Kawanishi", "Japan", "Asia/Tokyo"),
  ("Kawasaki", "Japan", "Asia/Tokyo"),
  ("Kiryū", "Japan", "Asia/Tokyo"),
  ("Kisarazu", "Japan", "Asia/Tokyo"),
  ("Kishiwada", "Japan", "Asia/Tokyo"),
  ("Kitakyushu", "Japan", "Asia/Tokyo"),
  ("Kitami", "Japan", "Asia/Tokyo"),
  ("Kobe", "Japan", "Asia/Tokyo"),
  ("Kochi", "Japan", "Asia/Tokyo"),
  ("Kokubunji", "Japan", "Asia/Tokyo"),
  ("Komaki", "Japan", "Asia/Tokyo"),
  ("Komatsu", "Japan", "Asia/Tokyo"),
  ("Koshigaya", "Japan", "Asia/Tokyo"),
  ("Kumagaya", "Japan", "Asia/Tokyo"),
  ("Kumamoto", "Japan", "Asia/Tokyo"),
  ("Kurashiki", "Japan", "Asia/Tokyo"),
  ("Kure", "Japan", "Asia/Tokyo"),
  ("Kurume", "Japan", "Asia/Tokyo"),
  ("Kusatsu", "Japan", "Asia/Tokyo"),
  ("Kushiro", "Japan", "Asia/Tokyo"),
  ("Kyoto", "Japan", "Asia/Tokyo"),
  ("Kōfu", "Japan", "Asia/Tokyo"),
  ("Kōnan", "Japan", "Asia/Tokyo"),
  ("Kōriyama", "Japan", "Asia/Tokyo"),
  ("Machida", "Japan", "Asia/Tokyo"),
  ("Maebashi", "Japan", "Asia/Tokyo"),
  ("Matsubara", "Japan", "Asia/Tokyo"),
  ("Matsudo", "Japan", "Asia/Tokyo"),
  ("Matsue", "Japan", "Asia/Tokyo"),
  ("Matsumoto", "Japan", "Asia/Tokyo"),
  ("Matsuyama", "Japan", "Asia/Tokyo"),
  ("Minamirinkan", "Japan", "Asia/Tokyo"),
  ("Minato", "Japan", "Asia/Tokyo"),
  ("Mino", "Japan", "Asia/Tokyo"),
  ("Mishima", "Japan", "Asia/Tokyo"),
  ("Mitaka-shi", "Japan", "Asia/Tokyo"),
  ("Mito", "Japan", "Asia/Tokyo"),
  ("Miyakonojō", "Japan", "Asia/Tokyo"),
  ("Miyazaki", "Japan", "Asia/Tokyo"),
  ("Moriguchi", "Japan", "Asia/Tokyo"),
  ("Morioka", "Japan", "Asia/Tokyo"),
  ("Musashino", "Japan", "Asia/Tokyo"),
  ("Nagano", "Japan", "Asia/Tokyo"),
  ("Nagaoka", "Japan", "Asia/Tokyo"),
  ("Nagareyama", "Japan", "Asia/Tokyo"),
  ("Nagasaki", "Japan", "Asia/Tokyo"),
  ("Nagoya", "Japan", "Asia/Tokyo"),
  ("Naha", "Japan", "Asia/Tokyo"),
  ("Nara-shi", "Japan", "Asia/Tokyo"),
  ("Narita", "Japan", "Asia/Tokyo"),
  ("Neyagawa", "Japan", "Asia/Tokyo"),
  ("Niigata", "Japan", "Asia/Tokyo"),
  ("Niihama", "Japan", "Asia/Tokyo"),
  ("Nishi-Tokyo-shi", "Japan", "Asia/Tokyo"),
  ("Nishinomiya-hama", "Japan", "Asia/Tokyo"),
  ("Nishio", "Japan", "Asia/Tokyo"),
  ("Nobeoka", "Japan", "Asia/Tokyo"),
  ("Noda", "Japan", "Asia/Tokyo"),
  ("Numazu", "Japan", "Asia/Tokyo"),
  ("Obihiro", "Japan", "Asia/Tokyo"),
  ("Odawara", "Japan", "Asia/Tokyo"),
  ("Okayama", "Japan", "Asia/Tokyo"),
  ("Okazaki", "Japan", "Asia/Tokyo"),
  ("Okinawa", "Japan", "Asia/Tokyo"),
  ("Osaka", "Japan", "Asia/Tokyo"),
  ("Otaru", "Japan", "Asia/Tokyo"),
  ("Oyama", "Japan", "Asia/Tokyo"),
  ("Saga", "Japan", "Asia/Tokyo"),
  ("Saitama", "Japan", "Asia/Tokyo"),
  ("Sakai", "Japan", "Asia/Tokyo"),
  ("Sakata", "Japan", "Asia/Tokyo"),
  ("Sakura", "Japan", "Asia/Tokyo"),
  ("Sandachō", "Japan", "Asia/Tokyo"),
  ("Sapporo", "Japan", "Asia/Tokyo"),
  ("Sasebo", "Japan", "Asia/Tokyo"),
  ("Sayama", "Japan", "Asia/Tokyo"),
  ("Sendai", "Japan", "Asia/Tokyo"),
  ("Seto", "Japan", "Asia/Tokyo"),
  ("Shimonoseki", "Japan", "Asia/Tokyo"),
  ("Shimotoda", "Japan", "Asia/Tokyo"),
  ("Shizuoka", "Japan", "Asia/Tokyo"),
  ("Suita", "Japan", "Asia/Tokyo"),
  ("Suzuka", "Japan", "Asia/Tokyo"),
  ("Sōka", "Japan", "Asia/Tokyo"),
  ("Tajimi", "Japan", "Asia/Tokyo"),
  ("Takamatsu", "Japan", "Asia/Tokyo"),
  ("Takaoka", "Japan", "Asia/Tokyo"),
  ("Takarazuka", "Japan", "Asia/Tokyo"),
  ("Takasaki", "Japan", "Asia/Tokyo"),
  ("Takatsuki", "Japan", "Asia/Tokyo"),
  ("Tokorozawa", "Japan", "Asia/Tokyo"),
  ("Tokushima", "Japan", "Asia/Tokyo"),
  ("Tokuyama", "Japan", "Asia/Tokyo"),
  ("Tokyo", "Japan", "Asia/Tokyo"),
  ("Tomakomai", "Japan", "Asia/Tokyo"),
  ("Tondabayashichō", "Japan", "Asia/Tokyo"),
  ("Tottori", "Japan", "Asia/Tokyo"),
  ("Toyama", "Japan", "Asia/Tokyo"),
  ("Toyohashi", "Japan", "Asia/Tokyo"),
  ("Toyokawa", "Japan", "Asia/Tokyo"),
  ("Toyonaka", "Japan", "Asia/Tokyo"),
  ("Toyota", "Japan", "Asia/Tokyo"),
  ("Tsu", "Japan", "Asia/Tokyo"),
  ("Tsukuba", "Japan", "Asia/Tokyo"),
  ("Ube", "Japan", "Asia/Tokyo"),
  ("Ueda", "Japan", "Asia/Tokyo"),
  ("Uji", "Japan", "Asia/Tokyo"),
  ("Urayasu", "Japan", "Asia/Tokyo"),
  ("Utsunomiya", "Japan", "Asia/Tokyo"),
  ("Wakayama", "Japan", "Asia/Tokyo"),
  ("Yaizu", "Japan", "Asia/Tokyo"),
  ("Yamagata", "Japan", "Asia/Tokyo"),
  ("Yamaguchi", "Japan", "Asia/Tokyo"),
  ("Yao", "Japan", "Asia/Tokyo"),
  ("Yokkaichi", "Japan", "Asia/Tokyo"),
  ("Yokohama", "Japan", "Asia/Tokyo"),
  ("Yokosuka", "Japan", "Asia/Tokyo"),
  ("Yonago", "Japan", "Asia/Tokyo"),
  ("Yono", "Japan", "Asia/Tokyo"),
  ("Zama", "Japan", "Asia/Tokyo"),
  ("Ōgaki", "Japan", "Asia/Tokyo"),
  ("Ōita", "Japan", "Asia/Tokyo"),
  ("Ōme", "Japan", "Asia/Tokyo"),
  ("Ōmuta", "Japan", "Asia/Tokyo"),
  ("Ōta", "Japan", "Asia/Tokyo"),
  ("Ōtsu", "Japan", "Asia/Tokyo"),
  ("Andong", "Korea", "Asia/Seoul"),
  ("Ansan-si", "Korea", "Asia/Seoul"),
  ("Anyang-si", "Korea", "Asia/Seoul"),
  ("Bucheon-si", "Korea", "Asia/Seoul"),
  ("Busan", "Korea", "Asia/Seoul"),
  ("Changwon", "Korea", "Asia/Seoul"),
  ("Cheonan", "Korea", "Asia/Seoul"),
  ("Cheongju-si", "Korea", "Asia/Seoul"),
  ("Chinju", "Korea", "Asia/Seoul"),
  ("Chuncheon", "Korea", "Asia/Seoul"),
  ("Daegu", "Korea", "Asia/Seoul"),
  ("Daejeon", "Korea", "Asia/Seoul"),
  ("Gimcheon", "Korea", "Asia/Seoul"),
  ("Goyang-si", "Korea", "Asia/Seoul"),
  ("Gumi", "Korea", "Asia/Seoul"),
  ("Gunsan", "Korea", "Asia/Seoul"),
  ("Guri-si", "Korea", "Asia/Seoul"),
  ("Gwangju", "Korea", "Asia/Seoul"),
  ("Gyeongsan-si", "Korea", "Asia/Seoul"),
  ("Hanam", "Korea", "Asia/Seoul"),
  ("Hwado", "Korea", "Asia/Seoul"),
  ("Hwaseong-si", "Korea", "Asia/Seoul"),
  ("Icheon-si", "Korea", "Asia/Seoul"),
  ("Iksan", "Korea", "Asia/Seoul"),
  ("Incheon", "Korea", "Asia/Seoul"),
  ("Jeju City", "Korea", "Asia/Seoul"),
  ("Jeonju", "Korea", "Asia/Seoul"),
  ("Kang-neung", "Korea", "Asia/Seoul"),
  ("Kimhae", "Korea", "Asia/Seoul"),
  ("Kwangmyŏng", "Korea", "Asia/Seoul"),
  ("Kyonju", "Korea", "Asia/Seoul"),
  ("Moppo", "Korea", "Asia/Seoul"),
  ("Osan", "Korea", "Asia/Seoul"),
  ("Pohang", "Korea", "Asia/Seoul"),
  ("Seogwipo", "Korea", "Asia/Seoul"),
  ("Seongnam-si", "Korea", "Asia/Seoul"),
  ("Seoul", "Korea", "Asia/Seoul"),
  ("Suncheon", "Korea", "Asia/Seoul"),
  ("Suwon-si", "Korea", "Asia/Seoul"),
  ("Tonghae", "Korea", "Asia/Seoul"),
  ("Uijeongbu-si", "Korea", "Asia/Seoul"),
  ("Ulsan", "Korea", "Asia/Seoul"),
  ("Wŏnju", "Korea", "Asia/Seoul"),
  ("Yangju", "Korea", "Asia/Seoul"),
  ("Yeosu", "Korea", "Asia/Seoul"),
  ("Daugavpils", "Latvia", "Europe/Riga"),
  ("Riga", "Latvia", "Europe/Riga"),
  ("Kaunas", "Lithuania", "Europe/Vilnius"),
  ("Klaipėda", "Lithuania", "Europe/Vilnius"),
  ("Panevėžys", "Lithuania", "Europe/Vilnius"),
  ("Vilnius", "Lithuania", "Europe/Vilnius"),
  ("Šiauliai", "Lithuania", "Europe/Vilnius"),
  ("Acapulco de Juárez", "Mexico", "America/Mexico_City"),
  ("Aguascalientes", "Mexico", "America/Mexico_City"),
  ("Azcapotzalco", "Mexico", "America/Mexico_City"),
  ("Benito Juarez", "Mexico", "America/Mexico_City"),
  ("Buenavista", "Mexico", "America/Mexico_City"),
  ("Campeche", "Mexico", "America/Merida"),
  ("Cancún", "Mexico", "America/Cancun"),
  ("Celaya", "Mexico", "America/Mexico_City"),
  ("Chalco", "Mexico", "America/Mexico_City"),
  ("Chetumal", "Mexico", "America/Cancun"),
  ("Chihuahua", "Mexico", "America/Chihuahua"),
  ("Chilpancingo", "Mexico", "America/Mexico_City"),
  ("Cholula", "Mexico", "America/Mexico_City"),
  ("Ciudad Acuña", "Mexico", "America/Matamoros"),
  ("Ciudad Apodaca", "Mexico", "America/Monterrey"),
  ("Ciudad Delicias", "Mexico", "America/Chihuahua"),
  ("Ciudad General Escobedo", "Mexico", "America/Monterrey"),
  ("Ciudad Guzmán", "Mexico", "America/Mexico_City"),
  ("Ciudad Juárez", "Mexico", "America/Ojinaga"),
  ("Ciudad López Mateos", "Mexico", "America/Mexico_City"),
  ("Ciudad Madero", "Mexico", "America/Monterrey"),
  ("Ciudad Nezahualcoyotl", "Mexico", "America/Mexico_City"),
  ("Ciudad Obregón", "Mexico", "America/Hermosillo"),
  ("Ciudad Valles", "Mexico", "America/Mexico_City"),
  ("Ciudad Victoria", "Mexico", "America/Monterrey"),
  ("Ciudad de Villa de Álvarez", "Mexico", "America/Mexico_City"),
  ("Ciudad del Carmen", "Mexico", "America/Merida"),
  ("Coacalco", "Mexico", "America/Mexico_City"),
  ("Coatzacoalcos", "Mexico", "America/Mexico_City"),
  ("Colima", "Mexico", "America/Mexico_City"),
  ("Coyoacán", "Mexico", "America/Mexico_City"),
  ("Cuajimalpa", "Mexico", "America/Mexico_City"),
  ("Cuauhtémoc", "Mexico", "America/Mexico_City"),
  ("Cuautitlán Izcalli", "Mexico", "America/Mexico_City"),
  ("Cuautla", "Mexico", "America/Mexico_City"),
  ("Cuernavaca", "Mexico", "America/Mexico_City"),
  ("Culiacán", "Mexico", "America/Mazatlan"),
  ("Córdoba", "Mexico", "America/Mexico_City"),
  ("Ecatepec", "Mexico", "America/Mexico_City"),
  ("Ensenada", "Mexico", "America/Tijuana"),
  ("Fresnillo", "Mexico", "America/Mexico_City"),
  ("Garza García", "Mexico", "America/Monterrey"),
  ("Gomez Palacio", "Mexico", "America/Monterrey"),
  ("Guadalajara", "Mexico", "America/Mexico_City"),
  ("Guadalupe", "Mexico", "America/Monterrey"),
  ("Hermosillo", "Mexico", "America/Hermosillo"),
  ("Heroica Guaymas", "Mexico", "America/Hermosillo"),
  ("Heroica Matamoros", "Mexico", "America/Matamoros"),
  ("Huixquilucan", "Mexico", "America/Mexico_City"),
  ("Iguala de la Independencia", "Mexico", "America/Mexico_City"),
  ("Irapuato", "Mexico", "America/Mexico_City"),
  ("Ixtapaluca", "Mexico", "America/Mexico_City"),
  ("Iztacalco", "Mexico", "America/Mexico_City"),
  ("Iztapalapa", "Mexico", "America/Mexico_City"),
  ("Jiutepec", "Mexico", "America/Mexico_City"),
  ("La Paz", "Mexico", "America/Mazatlan"),
  ("Las Margaritas", "Mexico", "America/Mexico_City"),
  ("León de los Aldama", "Mexico", "America/Mexico_City"),
  ("Los Mochis", "Mexico", "America/Mazatlan"),
  ("Los Reyes Acaquilpan", "Mexico", "America/Mexico_City"),
  ("Magdalena Contreras", "Mexico", "America/Mexico_City"),
  ("Manzanillo", "Mexico", "America/Mexico_City"),
  ("Manzanillo", "Mexico", "America/Mexico_City"),
  ("Martínez de la Torre", "Mexico", "America/Mexico_City"),
  ("Matamoros", "Mexico", "America/Monterrey"),
  ("Mazatlán", "Mexico", "America/Mazatlan"),
  ("Metepec", "Mexico", "America/Mexico_City"),
  ("Mexicali", "Mexico", "America/Tijuana"),
  ("Mexico City", "Mexico", "America/Mexico_City"),
  ("Miguel Hidalgo", "Mexico", "America/Mexico_City"),
  ("Milpa Alta", "Mexico", "America/Mexico_City"),
  ("Minatitlan", "Mexico", "America/Mexico_City"),
  ("Monclova", "Mexico", "America/Monterrey"),
  ("Monterrey", "Mexico", "America/Monterrey"),
  ("Morelia", "Mexico", "America/Mexico_City"),
  ("Mérida", "Mexico", "America/Merida"),
  ("Naucalpan de Juárez", "Mexico", "America/Mexico_City"),
  ("Naucalpan de Juárez", "Mexico", "America/Mexico_City"),
  ("Navojoa", "Mexico", "America/Hermosillo"),
  ("Nicolás Romero", "Mexico", "America/Mexico_City"),
  ("Nogales", "Mexico", "America/Hermosillo"),
  ("Nuevo Laredo", "Mexico", "America/Matamoros"),
  ("Oaxaca", "Mexico", "America/Mexico_City"),
  ("Ojo de Agua", "Mexico", "America/Mexico_City"),
  ("Orizaba", "Mexico", "America/Mexico_City"),
  ("Pachuca de Soto", "Mexico", "America/Mexico_City"),
  ("Parral", "Mexico", "America/Chihuahua"),
  ("Piedras Negras", "Mexico", "America/Matamoros"),
  ("Playa del Carmen", "Mexico", "America/Cancun"),
  ("Poza Rica de Hidalgo", "Mexico", "America/Mexico_City"),
  ("Puebla", "Mexico", "America/Mexico_City"),
  ("Puerto Vallarta", "Mexico", "America/Mexico_City"),
  ("Reynosa", "Mexico", "America/Matamoros"),
  ("Salamanca", "Mexico", "America/Mexico_City"),
  ("Saltillo", "Mexico", "America/Monterrey"),
  ("San Cristóbal de las Casas", "Mexico", "America/Mexico_City"),
  ("San Juan del Río", "Mexico", "America/Mexico_City"),
  ("San Luis Potosí", "Mexico", "America/Mexico_City"),
  ("San Luis Río Colorado", "Mexico", "America/Hermosillo"),
  ("San Miguel Xico Viejo", "Mexico", "America/Mexico_City"),
  ("San Nicolás de los Garza", "Mexico", "America/Monterrey"),
  ("San Pablo de las Salinas", "Mexico", "America/Mexico_City"),
  ("San Pedro Garza Garcia", "Mexico", "America/Monterrey"),
  ("Santa Catarina", "Mexico", "America/Monterrey"),
  ("Santa María Chimalhuacán", "Mexico", "America/Mexico_City"),
  ("Santiago de Querétaro", "Mexico", "America/Mexico_City"),
  ("Soledad de Graciano Sánchez", "Mexico", "America/Mexico_City"),
  ("Soledad de Graciano Sánchez", "Mexico", "America/Mexico_City"),
  ("Tampico", "Mexico", "America/Monterrey"),
  ("Tampico", "Mexico", "America/Monterrey"),
  ("Tantoyuca", "Mexico", "America/Mexico_City"),
  ("Tapachula", "Mexico", "America/Mexico_City"),
  ("Tehuacán", "Mexico", "America/Mexico_City"),
  ("Temapache", "Mexico", "America/Mexico_City"),
  ("Tepic", "Mexico", "America/Mazatlan"),
  ("Texcoco", "Mexico", "America/Mexico_City"),
  ("Tijuana", "Mexico", "America/Tijuana"),
  ("Tlahuac", "Mexico", "America/Mexico_City"),
  ("Tlalnepantla", "Mexico", "America/Mexico_City"),
  ("Tlalpan", "Mexico", "America/Mexico_City"),
  ("Tlaquepaque", "Mexico", "America/Mexico_City"),
  ("Toluca", "Mexico", "America/Mexico_City"),
  ("Tonalá", "Mexico", "America/Mexico_City"),
  ("Torreon", "Mexico", "America/Monterrey"),
  ("Tulancingo", "Mexico", "America/Mexico_City"),
  ("Tuxtla", "Mexico", "America/Mexico_City"),
  ("Túxpam de Rodríguez Cano", "Mexico", "America/Mexico_City"),
  ("Uruapan", "Mexico", "America/Mexico_City"),
  ("Venustiano Carranza", "Mexico", "America/Mexico_City"),
  ("Veracruz", "Mexico", "America/Mexico_City"),
  ("Victoria de Durango", "Mexico", "America/Monterrey"),
  ("Villahermosa", "Mexico", "America/Mexico_City"),
  ("Xalapa de Enríquez", "Mexico", "America/Mexico_City"),
  ("Xochimilco", "Mexico", "America/Mexico_City"),
  ("Zacatecas", "Mexico", "America/Mexico_City"),
  ("Zamora", "Mexico", "America/Mexico_City"),
  ("Zapopan", "Mexico", "America/Mexico_City"),
  ("'s-Hertogenbosch", "Netherlands", "Europe/Amsterdam"),
  ("Almere Stad", "Netherlands", "Europe/Amsterdam"),
  ("Amersfoort", "Netherlands", "Europe/Amsterdam"),
  ("Amsterdam", "Netherlands", "Europe/Amsterdam"),
  ("Apeldoorn", "Netherlands", "Europe/Amsterdam"),
  ("Arnhem", "Netherlands", "Europe/Amsterdam"),
  ("Breda", "Netherlands", "Europe/Amsterdam"),
  ("Dordrecht", "Netherlands", "Europe/Amsterdam"),
  ("Eindhoven", "Netherlands", "Europe/Amsterdam"),
  ("Enschede", "Netherlands", "Europe/Amsterdam"),
  ("Groningen", "Netherlands", "Europe/Amsterdam"),
  ("Haarlem", "Netherlands", "Europe/Amsterdam"),
  ("Hoofddorp", "Netherlands", "Europe/Amsterdam"),
  ("Leiden", "Netherlands", "Europe/Amsterdam"),
  ("Maastricht", "Netherlands", "Europe/Amsterdam"),
  ("Nijmegen", "Netherlands", "Europe/Amsterdam"),
  ("Rotterdam", "Netherlands", "Europe/Amsterdam"),
  ("The Hague", "Netherlands", "Europe/Amsterdam"),
  ("Tilburg", "Netherlands", "Europe/Amsterdam"),
  ("Utrecht", "Netherlands", "Europe/Amsterdam"),
  ("Zaanstad", "Netherlands", "Europe/Amsterdam"),
  ("Zoetermeer", "Netherlands", "Europe/Amsterdam"),
  ("Zwolle", "Netherlands", "Europe/Amsterdam"),
  ("Auckland", "New Zealand", "Pacific/Auckland"),
  ("Christchurch", "New Zealand", "Pacific/Auckland"),
  ("Dunedin", "New Zealand", "Pacific/Auckland"),
  ("Hamilton", "New Zealand", "Pacific/Auckland"),
  ("Lower Hutt", "New Zealand", "Pacific/Auckland"),
  ("Manukau City", "New Zealand", "Pacific/Auckland"),
  ("Tauranga", "New Zealand", "Pacific/Auckland"),
  ("Waitakere", "New Zealand", "Pacific/Auckland"),
  ("Wellington", "New Zealand", "Pacific/Auckland"),
  ("Bergen", "Norway", "Europe/Oslo"),
  ("Oslo", "Norway", "Europe/Oslo"),
  ("Stavanger", "Norway", "Europe/Oslo"),
  ("Trondheim", "Norway", "Europe/Oslo"),
  ("Bemowo", "Poland", "Europe/Warsaw"),
  ("Białystok", "Poland", "Europe/Warsaw"),
  ("Bielany", "Poland", "Europe/Warsaw"),
  ("Bielsko-Biala", "Poland", "Europe/Warsaw"),
  ("Bydgoszcz", "Poland", "Europe/Warsaw"),
  ("Bytom", "Poland", "Europe/Warsaw"),
  ("Chorzów", "Poland", "Europe/Warsaw"),
  ("Częstochowa", "Poland", "Europe/Warsaw"),
  ("Dąbrowa Górnicza", "Poland", "Europe/Warsaw"),
  ("Elbląg", "Poland", "Europe/Warsaw"),
  ("Gdańsk", "Poland", "Europe/Warsaw"),
  ("Gdynia", "Poland", "Europe/Warsaw"),
  ("Gliwice", "Poland", "Europe/Warsaw"),
  ("Gorzów Wielkopolski", "Poland", "Europe/Warsaw"),
  ("Kalisz", "Poland", "Europe/Warsaw"),
  ("Katowice", "Poland", "Europe/Warsaw"),
  ("Kielce", "Poland", "Europe/Warsaw"),
  ("Koszalin", "Poland", "Europe/Warsaw"),
  ("Kraków", "Poland", "Europe/Warsaw"),
  ("Legnica", "Poland", "Europe/Warsaw"),
  ("Lublin", "Poland", "Europe/Warsaw"),
  ("Mokotów", "Poland", "Europe/Warsaw"),
  ("Olsztyn", "Poland", "Europe/Warsaw"),
  ("Opole", "Poland", "Europe/Warsaw"),
  ("Poznań", "Poland", "Europe/Warsaw"),
  ("Praga Południe", "Poland", "Europe/Warsaw"),
  ("Płock", "Poland", "Europe/Warsaw"),
  ("Radom", "Poland", "Europe/Warsaw"),
  ("Ruda Śląska", "Poland", "Europe/Warsaw"),
  ("Rybnik", "Poland", "Europe/Warsaw"),
  ("Rzeszów", "Poland", "Europe/Warsaw"),
  ("Sosnowiec", "Poland", "Europe/Warsaw"),
  ("Szczecin", "Poland", "Europe/Warsaw"),
  ("Targówek", "Poland", "Europe/Warsaw"),
  ("Tarnów", "Poland", "Europe/Warsaw"),
  ("Toruń", "Poland", "Europe/Warsaw"),
  ("Tychy", "Poland", "Europe/Warsaw"),
  ("Ursynów", "Poland", "Europe/Warsaw"),
  ("Warsaw", "Poland", "Europe/Warsaw"),
  ("Wałbrzych", "Poland", "Europe/Warsaw"),
  ("Wola", "Poland", "Europe/Warsaw"),
  ("Wrocław", "Poland", "Europe/Warsaw"),
  ("Włocławek", "Poland", "Europe/Warsaw"),
  ("Zabrze", "Poland", "Europe/Warsaw"),
  ("Zielona Góra", "Poland", "Europe/Warsaw"),
  ("Łódź", "Poland", "Europe/Warsaw"),
  ("Śródmieście", "Poland", "Europe/Warsaw"),
  ("Amadora", "Portugal", "Europe/Lisbon"),
  ("Braga", "Portugal", "Europe/Lisbon"),
  ("Coimbra", "Portugal", "Europe/Lisbon"),
  ("Funchal", "Portugal", "Atlantic/Madeira"),
  ("Lisbon", "Portugal", "Europe/Lisbon"),
  ("Porto", "Portugal", "Europe/Lisbon"),
  ("Queluz", "Portugal", "Europe/Lisbon"),
  ("Setúbal", "Portugal", "Europe/Lisbon"),
  ("Bratislava", "Slovak Republic", "Europe/Bratislava"),
  ("Košice", "Slovak Republic", "Europe/Bratislava"),
  ("Ljubljana", "Slovenia", "Europe/Ljubljana"),
  ("A Coruña", "Spain", "Europe/Madrid"),
  ("Albacete", "Spain", "Europe/Madrid"),
  ("Alcalá de Henares", "Spain", "Europe/Madrid"),
  ("Alcobendas", "Spain", "Europe/Madrid"),
  ("Alcorcón", "Spain", "Europe/Madrid"),
  ("Algeciras", "Spain", "Europe/Madrid"),
  ("Alicante", "Spain", "Europe/Madrid"),
  ("Almería", "Spain", "Europe/Madrid"),
  ("Badajoz", "Spain", "Europe/Madrid"),
  ("Badalona", "Spain", "Europe/Madrid"),
  ("Barcelona", "Spain", "Europe/Madrid"),
  ("Bilbao", "Spain", "Europe/Madrid"),
  ("Burgos", "Spain", "Europe/Madrid"),
  ("Cadiz", "Spain", "Europe/Madrid"),
  ("Cartagena", "Spain", "Europe/Madrid"),
  ("Castelló de la Plana", "Spain", "Europe/Madrid"),
  ("Chamartín", "Spain", "Europe/Madrid"),
  ("Ciudad Lineal", "Spain", "Europe/Madrid"),
  ("Córdoba", "Spain", "Europe/Madrid"),
  ("Donostia / San Sebastián", "Spain", "Europe/Madrid"),
  ("Dos Hermanas", "Spain", "Europe/Madrid"),
  ("Elche", "Spain", "Europe/Madrid"),
  ("Fuenlabrada", "Spain", "Europe/Madrid"),
  ("Gasteiz / Vitoria", "Spain", "Europe/Madrid"),
  ("Getafe", "Spain", "Europe/Madrid"),
  ("Gijón", "Spain", "Europe/Madrid"),
  ("Granada", "Spain", "Europe/Madrid"),
  ("Huelva", "Spain", "Europe/Madrid"),
  ("Jaén", "Spain", "Europe/Madrid"),
  ("Jerez de la Frontera", "Spain", "Europe/Madrid"),
  ("L'Hospitalet de Llobregat", "Spain", "Europe/Madrid"),
  ("La Laguna", "Spain", "Atlantic/Canary"),
  ("Las Palmas de Gran Canaria", "Spain", "Atlantic/Canary"),
  ("Leganés", "Spain", "Europe/Madrid"),
  ("León", "Spain", "Europe/Madrid"),
  ("Lleida", "Spain", "Europe/Madrid"),
  ("Logroño", "Spain", "Europe/Madrid"),
  ("Madrid", "Spain", "Europe/Madrid"),
  ("Marbella", "Spain", "Europe/Madrid"),
  ("Mataró", "Spain", "Europe/Madrid"),
  ("Murcia", "Spain", "Europe/Madrid"),
  ("Málaga", "Spain", "Europe/Madrid"),
  ("Móstoles", "Spain", "Europe/Madrid"),
  ("Ourense", "Spain", "Europe/Madrid"),
  ("Oviedo", "Spain", "Europe/Madrid"),
  ("Palma", "Spain", "Europe/Madrid"),
  ("Pamplona", "Spain", "Europe/Madrid"),
  ("Parla", "Spain", "Europe/Madrid"),
  ("Reus", "Spain", "Europe/Madrid"),
  ("Sabadell", "Spain", "Europe/Madrid"),
  ("Salamanca", "Spain", "Europe/Madrid"),
  ("Santa Coloma de Gramenet", "Spain", "Europe/Madrid"),
  ("Santa Cruz de Tenerife", "Spain", "Atlantic/Canary"),
  ("Santander", "Spain", "Europe/Madrid"),
  ("Sevilla", "Spain", "Europe/Madrid"),
  ("Tarragona", "Spain", "Europe/Madrid"),
  ("Telde", "Spain", "Atlantic/Canary"),
  ("Terrassa", "Spain", "Europe/Madrid"),
  ("Torrejón de Ardoz", "Spain", "Europe/Madrid"),
  ("Torrevieja", "Spain", "Europe/Madrid"),
  ("Valencia", "Spain", "Europe/Madrid"),
  ("Valladolid", "Spain", "Europe/Madrid"),
  ("Vigo", "Spain", "Europe/Madrid"),
  ("Zaragoza", "Spain", "Europe/Madrid"),
  ("Göteborg", "Sweden", "Europe/Stockholm"),
  ("Malmö", "Sweden", "Europe/Stockholm"),
  ("Stockholm", "Sweden", "Europe/Stockholm"),
  ("Uppsala", "Sweden", "Europe/Stockholm"),
  ("Västerås", "Sweden", "Europe/Stockholm"),
  ("Basel", "Switzerland", "Europe/Zurich"),
  ("Bern", "Switzerland", "Europe/Zurich"),
  ("Genève", "Switzerland", "Europe/Zurich"),
  ("Lausanne", "Switzerland", "Europe/Zurich"),
  ("Zürich", "Switzerland", "Europe/Zurich"),
  ("Adana", "Türkiye", "Europe/Istanbul"),
  ("Adapazarı", "Türkiye", "Europe/Istanbul"),
  ("Adıyaman", "Türkiye", "Europe/Istanbul"),
  ("Afyonkarahisar", "Türkiye", "Europe/Istanbul"),
  ("Aksaray", "Türkiye", "Europe/Istanbul"),
  ("Alanya", "Türkiye", "Europe/Istanbul"),
  ("Ankara", "Türkiye", "Europe/Istanbul"),
  ("Antakya", "Türkiye", "Europe/Istanbul"),
  ("Antalya", "Türkiye", "Europe/Istanbul"),
  ("Ataşehir", "Türkiye", "Europe/Istanbul"),
  ("Aydın", "Türkiye", "Europe/Istanbul"),
  ("Bahçelievler", "Türkiye", "Europe/Istanbul"),
  ("Balıkesir", "Türkiye", "Europe/Istanbul"),
  ("Bandırma", "Türkiye", "Europe/Istanbul"),
  ("Batikent", "Türkiye", "Europe/Istanbul"),
  ("Batman", "Türkiye", "Europe/Istanbul"),
  ("Bağcılar", "Türkiye", "Europe/Istanbul"),
  ("Başakşehir", "Türkiye", "Europe/Istanbul"),
  ("Beylikdüzü", "Türkiye", "Europe/Istanbul"),
  ("Bursa", "Türkiye", "Europe/Istanbul"),
  ("Büyükçekmece", "Türkiye", "Europe/Istanbul"),
  ("Denizli", "Türkiye", "Europe/Istanbul"),
  ("Diyarbakır", "Türkiye", "Europe/Istanbul"),
  ("Edirne", "Türkiye", "Europe/Istanbul"),
  ("Elazığ", "Türkiye", "Europe/Istanbul"),
  ("Erzincan", "Türkiye", "Europe/Istanbul"),
  ("Erzurum", "Türkiye", "Europe/Istanbul"),
  ("Esenler", "Türkiye", "Europe/Istanbul"),
  ("Esenyurt", "Türkiye", "Europe/Istanbul"),
  ("Eskişehir", "Türkiye", "Europe/Istanbul"),
  ("Gaziantep", "Türkiye", "Europe/Istanbul"),
  ("Gebze", "Türkiye", "Europe/Istanbul"),
  ("Kahramanmaraş", "Türkiye", "Europe/Istanbul"),
  ("Karabağlar", "Türkiye", "Europe/Istanbul"),
  ("Karaman", "Türkiye", "Europe/Istanbul"),
  ("Kayseri", "Türkiye", "Europe/Istanbul"),
  ("Konya", "Türkiye", "Europe/Istanbul"),
  ("Kütahya", "Türkiye", "Europe/Istanbul"),
  ("Kırıkkale", "Türkiye", "Europe/Istanbul"),
  ("Kızıltepe", "Türkiye", "Europe/Istanbul"),
  ("Malatya", "Türkiye", "Europe/Istanbul"),
  ("Maltepe", "Türkiye", "Europe/Istanbul"),
  ("Manisa", "Türkiye", "Europe/Istanbul"),
  ("Mercin", "Türkiye", "Europe/Istanbul"),
  ("Merkezefendi", "Türkiye", "Europe/Istanbul"),
  ("Muratpaşa", "Türkiye", "Europe/Istanbul"),
  ("Mustafakemalpaşa", "Türkiye", "Europe/Istanbul"),
  ("Nazilli", "Türkiye", "Europe/Istanbul"),
  ("Ordu", "Türkiye", "Europe/Istanbul"),
  ("Osmaniye", "Türkiye", "Europe/Istanbul"),
  ("Samsun", "Türkiye", "Europe/Istanbul"),
  ("Sancaktepe", "Türkiye", "Europe/Istanbul"),
  ("Siirt", "Türkiye", "Europe/Istanbul"),
  ("Sivas", "Türkiye", "Europe/Istanbul"),
  ("Siverek", "Türkiye", "Europe/Istanbul"),
  ("Sultanbeyli", "Türkiye", "Europe/Istanbul"),
  ("Sultangazi", "Türkiye", "Europe/Istanbul"),
  ("Tarsus", "Türkiye", "Europe/Istanbul"),
  ("Tekirdağ", "Türkiye", "Europe/Istanbul"),
  ("Tokat", "Türkiye", "Europe/Istanbul"),
  ("Trabzon", "Türkiye", "Europe/Istanbul"),
  ("Turgutlu", "Türkiye", "Europe/Istanbul"),
  ("Turhal", "Türkiye", "Europe/Istanbul"),
  ("Umraniye", "Türkiye", "Europe/Istanbul"),
  ("Uşak", "Türkiye", "Europe/Istanbul"),
  ("Van", "Türkiye", "Europe/Istanbul"),
  ("Viranşehir", "Türkiye", "Europe/Istanbul"),
  ("Zeytinburnu", "Türkiye", "Europe/Istanbul"),
  ("Zonguldak", "Türkiye", "Europe/Istanbul"),
  ("Çankaya", "Türkiye", "Europe/Istanbul"),
  ("Çorlu", "Türkiye", "Europe/Istanbul"),
  ("Çorum", "Türkiye", "Europe/Istanbul"),
  ("Üsküdar", "Türkiye", "Europe/Istanbul"),
  ("İnegol", "Türkiye", "Europe/Istanbul"),
  ("İstanbul", "Türkiye", "Europe/Istanbul"),
  ("İzmir", "Türkiye", "Europe/Istanbul"),
  ("İzmit", "Türkiye", "Europe/Istanbul"),
  ("Şanlıurfa", "Türkiye", "Europe/Istanbul"),
  ("Şişli", "Türkiye", "Europe/Istanbul"),
  ("Aberdeen", "United Kingdom", "Europe/London"),
  ("Basildon", "United Kingdom", "Europe/London"),
  ("Belfast", "United Kingdom", "Europe/London"),
  ("Birmingham", "United Kingdom", "Europe/London"),
  ("Blackburn", "United Kingdom", "Europe/London"),
  ("Blackpool", "United Kingdom", "Europe/London"),
  ("Bolton", "United Kingdom", "Europe/London"),
  ("Bournemouth", "United Kingdom", "Europe/London"),
  ("Bradford", "United Kingdom", "Europe/London"),
  ("Brighton", "United Kingdom", "Europe/London"),
  ("Bristol", "United Kingdom", "Europe/London"),
  ("Cambridge", "United Kingdom", "Europe/London"),
  ("Cardiff", "United Kingdom", "Europe/London"),
  ("Chelmsford", "United Kingdom", "Europe/London"),
  ("Cheltenham", "United Kingdom", "Europe/London"),
  ("City of London", "United Kingdom", "Europe/London"),
  ("Hull", "United Kingdom", "Europe/London"),
  ("Irvine", "United Kingdom", "Europe/London"),
  ("Islington", "United Kingdom", "Europe/London"),
  ("Leeds", "United Kingdom", "Europe/London"),
  ("Leicester", "United Kingdom", "Europe/London"),
  ("Liverpool", "United Kingdom", "Europe/London"),
  ("London", "United Kingdom", "Europe/London"),
  ("Luton", "United Kingdom", "Europe/London"),
  ("Manchester", "United Kingdom", "Europe/London"),
  ("Middlesbrough", "United Kingdom", "Europe/London"),
  ("Milton Keynes", "United Kingdom", "Europe/London"),
  ("Newcastle upon Tyne", "United Kingdom", "Europe/London"),
  ("Newport", "United Kingdom", "Europe/London"),
  ("Northampton", "United Kingdom", "Europe/London"),
  ("Norwich", "United Kingdom", "Europe/London"),
  ("Nottingham", "United Kingdom", "Europe/London"),
  ("Oldham", "United Kingdom", "Europe/London"),
  ("Oxford", "United Kingdom", "Europe/London"),
  ("Peterborough", "United Kingdom", "Europe/London"),
  ("Plymouth", "United Kingdom", "Europe/London"),
  ("Poole", "United Kingdom", "Europe/London"),
  ("Portsmouth", "United Kingdom", "Europe/London"),
  ("Preston", "United Kingdom", "Europe/London"),
  ("Reading", "United Kingdom", "Europe/London"),
  ("Rotherham", "United Kingdom", "Europe/London"),
  ("Sheffield", "United Kingdom", "Europe/London"),
  ("Slough", "United Kingdom", "Europe/London"),
  ("Southampton", "United Kingdom", "Europe/London"),
  ("Southend-on-Sea", "United Kingdom", "Europe/London"),
  ("St Helens", "United Kingdom", "Europe/London"),
  ("Stockport", "United Kingdom", "Europe/London"),
  ("Stoke-on-Trent", "United Kingdom", "Europe/London"),
  ("Telford", "United Kingdom", "Europe/London"),
  ("Walsall", "United Kingdom", "Europe/London"),
  ("Watford", "United Kingdom", "Europe/London"),
  ("West Bromwich", "United Kingdom", "Europe/London"),
  ("Woking", "United Kingdom", "Europe/London"),
  ("Wolverhampton", "United Kingdom", "Europe/London"),
  ("Worcester", "United Kingdom", "Europe/London"),
  ("York", "United Kingdom", "Europe/London"),
  ("Abilene", "United States", "America/Chicago"),
  ("Akron", "United States", "America/New_York"),
  ("Albuquerque", "United States", "America/Denver"),
  ("Allentown", "United States", "America/New_York"),
  ("Amarillo", "United States", "America/Chicago"),
  ("Amherst", "United States", "America/New_York"),
  ("Anaheim", "United States", "America/Los_Angeles"),
  ("Anchorage", "United States", "America/Anchorage"),
  ("Ann Arbor", "United States", "America/Detroit"),
  ("Antioch", "United States", "America/Los_Angeles"),
  ("Arlington", "United States", "America/Chicago"),
  ("Arvada", "United States", "America/Denver"),
  ("Athens", "United States", "America/New_York"),
  ("Atlanta", "United States", "America/New_York"),
  ("Aurora", "United States", "America/Denver"),
  ("Aurora", "United States", "America/Chicago"),
  ("Austin", "United States", "America/Chicago"),
  ("Bakersfield", "United States", "America/Los_Angeles"),
  ("Baltimore", "United States", "America/New_York"),
  ("Baton Rouge", "United States", "America/Chicago"),
  ("Beaumont", "United States", "America/Chicago"),
  ("Bellevue", "United States", "America/Los_Angeles"),
  ("Berkeley", "United States", "America/Los_Angeles"),
  ("Billings", "United States", "America/Denver"),
  ("Birmingham", "United States", "America/Chicago"),
  ("Boise", "United States", "America/Boise"),
  ("Borough of Queens", "United States", "America/New_York"),
  ("Boston", "United States", "America/New_York"),
  ("Brandon", "United States", "America/New_York"),
  ("Bridgeport", "United States", "America/New_York"),
  ("Brooklyn", "United States", "America/New_York"),
  ("Brownsville", "United States", "America/Chicago"),
  ("Buffalo", "United States", "America/New_York"),
  ("Burbank", "United States", "America/Los_Angeles"),
  ("Cambridge", "United States", "America/New_York"),
  ("Cape Coral", "United States", "America/New_York"),
  ("Carlsbad", "United States", "America/Los_Angeles"),
  ("Carrollton", "United States", "America/Chicago"),
  ("Cary", "United States", "America/New_York"),
  ("Cedar Rapids", "United States", "America/Chicago"),
  ("Centennial", "United States", "America/Denver"),
  ("Chandler", "United States", "America/Phoenix"),
  ("Charleston", "United States", "America/New_York"),
  ("Charlotte", "United States", "America/New_York"),
  ("Chattanooga", "United States", "America/New_York"),
  ("Chicago", "United States", "America/Chicago"),
  ("Chula Vista", "United States", "America/Los_Angeles"),
  ("Cincinnati", "United States", "America/New_York"),
  ("Clarksville", "United States", "America/Chicago"),
  ("Clearwater", "United States", "America/New_York"),
  ("Cleveland", "United States", "America/New_York"),
  ("Colorado Springs", "United States", "America/Denver"),
  ("Columbia", "United States", "America/New_York"),
  ("Columbia", "United States", "America/Chicago"),
  ("Columbus", "United States", "America/New_York"),
  ("Columbus", "United States", "America/New_York"),
  ("Concord", "United States", "America/Los_Angeles"),
  ("Coral Springs", "United States", "America/New_York"),
  ("Corona", "United States", "America/Los_Angeles"),
  ("Corpus Christi", "United States", "America/Chicago"),
  ("Costa Mesa", "United States", "America/Los_Angeles"),
  ("Dallas", "United States", "America/Chicago"),
  ("Daly City", "United States", "America/Los_Angeles"),
  ("Dayton", "United States", "America/New_York"),
  ("Denton", "United States", "America/Chicago"),
  ("Denver", "United States", "America/Denver"),
  ("Des Moines", "United States", "America/Chicago"),
  ("Detroit", "United States", "America/Detroit"),
  ("Downey", "United States", "America/Los_Angeles"),
  ("Durham", "United States", "America/New_York"),
  ("East Chattanooga", "United States", "America/New_York"),
  ("East Independence", "United States", "America/Chicago"),
  ("East Los Angeles", "United States", "America/Los_Angeles"),
  ("Edison", "United States", "America/New_York"),
  ("El Monte", "United States", "America/Los_Angeles"),
  ("El Paso", "United States", "America/Denver"),
  ("Elgin", "United States", "America/Chicago"),
  ("Elizabeth", "United States", "America/New_York"),
  ("Elk Grove", "United States", "America/Los_Angeles"),
  ("Enterprise", "United States", "America/Los_Angeles"),
  ("Erie", "United States", "America/New_York"),
  ("Escondido", "United States", "America/Los_Angeles"),
  ("Eugene", "United States", "America/Los_Angeles"),
  ("Evansville", "United States", "America/Chicago"),
  ("Everett", "United States", "America/Los_Angeles"),
  ("Fairfield", "United States", "America/Los_Angeles"),
  ("Fargo", "United States", "America/Chicago"),
  ("Fayetteville", "United States", "America/New_York"),
  ("Flint", "United States", "America/Detroit"),
  ("Fontana", "United States", "America/Los_Angeles"),
  ("Fort Collins", "United States", "America/Denver"),
  ("Fort Lauderdale", "United States", "America/New_York"),
  ("Fort Wayne", "United States", "America/Indiana/Indianapolis"),
  ("Fort Worth", "United States", "America/Chicago"),
  ("Fremont", "United States", "America/Los_Angeles"),
  ("Fresno", "United States", "America/Los_Angeles"),
  ("Frisco", "United States", "America/Chicago"),
  ("Fullerton", "United States", "America/Los_Angeles"),
  ("Gainesville", "United States", "America/New_York"),
  ("Garden Grove", "United States", "America/Los_Angeles"),
  ("Garland", "United States", "America/Chicago"),
  ("Gilbert", "United States", "America/Phoenix"),
  ("Glendale", "United States", "America/Phoenix"),
  ("Glendale", "United States", "America/Los_Angeles"),
  ("Grand Prairie", "United States", "America/Chicago"),
  ("Grand Rapids", "United States", "America/Detroit"),
  ("Green Bay", "United States", "America/Chicago"),
  ("Greensboro", "United States", "America/New_York"),
  ("Gresham", "United States", "America/Los_Angeles"),
  ("Hayward", "United States", "America/Los_Angeles"),
  ("Henderson", "United States", "America/Los_Angeles"),
  ("Hialeah", "United States", "America/New_York"),
  ("High Point", "United States", "America/New_York"),
  ("Hollywood", "United States", "America/New_York"),
  ("Honolulu", "United States", "Pacific/Honolulu"),
  ("Houston", "United States", "America/Chicago"),
  ("Huntington Beach", "United States", "America/Los_Angeles"),
  ("Huntsville", "United States", "America/Chicago"),
  ("Independence", "United States", "America/Chicago"),
  ("Indianapolis", "United States", "America/Indiana/Indianapolis"),
  ("Inglewood", "United States", "America/Los_Angeles"),
  ("Ironville", "United States", "America/New_York"),
  ("Irving", "United States", "America/New_York"),
  ("Jackson", "United States", "America/Chicago"),
  ("Jacksonville", "United States", "America/New_York"),
  ("Jamaica", "United States", "America/New_York"),
  ("Jersey City", "United States", "America/New_York"),
  ("Joliet", "United States", "America/Chicago"),
  ("Kansas City", "United States", "America/Chicago"),
  ("Kansas City", "United States", "America/Chicago"),
  ("Knoxville", "United States", "America/New_York"),
  ("Lafayette", "United States", "America/Chicago"),
  ("Lakewood", "United States", "America/Denver"),
  ("Lansing", "United States", "America/Detroit"),
  ("Las Vegas", "United States", "America/Los_Angeles"),
  ("Lexington", "United States", "America/New_York"),
  ("Lexington-Fayette", "United States", "America/New_York"),
  ("Lincoln", "United States", "America/Chicago"),
  ("Little Rock", "United States", "America/Chicago"),
  ("Long Beach", "United States", "America/Los_Angeles"),
  ("Los Angeles", "United States", "America/Los_Angeles"),
  ("Louisville", "United States", "America/Kentucky/Louisville"),
  ("Lowell", "United States", "America/New_York"),
  ("Lubbock", "United States", "America/Chicago"),
  ("Madison", "United States", "America/Chicago"),
  ("Manchester", "United States", "America/New_York"),
  ("Manhattan", "United States", "America/New_York"),
  ("Meads", "United States", "America/New_York"),
  ("Memphis", "United States", "America/Chicago"),
  ("Mesa", "United States", "America/Phoenix"),
  ("Metairie", "United States", "America/Chicago"),
  ("Metairie Terrace", "United States", "America/Chicago"),
  ("Miami", "United States", "America/New_York"),
  ("Miami Gardens", "United States", "America/New_York"),
  ("Midland", "United States", "America/Chicago"),
  ("Milwaukee", "United States", "America/Chicago"),
  ("Minneapolis", "United States", "America/Chicago"),
  ("Miramar", "United States", "America/New_York"),
  ("Mobile", "United States", "America/Chicago"),
  ("Modesto", "United States", "America/Los_Angeles"),
  ("Montgomery", "United States", "America/Chicago"),
  ("Moreno Valley", "United States", "America/Los_Angeles"),
  ("Murfreesboro", "United States", "America/Chicago"),
  ("Murrieta", "United States", "America/Los_Angeles"),
  ("Naperville", "United States", "America/Chicago"),
  ("Nashville", "United States", "America/Chicago"),
  ("New Orleans", "United States", "America/Chicago"),
  ("New York City", "United States", "America/New_York"),
  ("Newark", "United States", "America/New_York"),
  ("Norman", "United States", "America/Chicago"),
  ("North Glendale", "United States", "America/Los_Angeles"),
  ("North Las Vegas", "United States", "America/Los_Angeles"),
  ("North Peoria", "United States", "America/Chicago"),
  ("Norwalk", "United States", "America/Los_Angeles"),
  ("Oakland", "United States", "America/Los_Angeles"),
  ("Oceanside", "United States", "America/Los_Angeles"),
  ("Oklahoma City", "United States", "America/Chicago"),
  ("Olathe", "United States", "America/Chicago"),
  ("Omaha", "United States", "America/Chicago"),
  ("Ontario", "United States", "America/Los_Angeles"),
  ("Orange", "United States", "America/Los_Angeles"),
  ("Orlando", "United States", "America/New_York"),
  ("Overland Park", "United States", "America/Chicago"),
  ("Oxnard", "United States", "America/Los_Angeles"),
  ("Oxnard Shores", "United States", "America/Los_Angeles"),
  ("Palm Bay", "United States", "America/New_York"),
  ("Palmdale", "United States", "America/Los_Angeles"),
  ("Paradise", "United States", "America/Los_Angeles"),
  ("Pasadena", "United States", "America/Los_Angeles"),
  ("Paterson", "United States", "America/New_York"),
  ("Pembroke Pines", "United States", "America/New_York"),
  ("Peoria", "United States", "America/Phoenix"),
  ("Peoria", "United States", "America/Chicago"),
  ("Philadelphia", "United States", "America/New_York"),
  ("Phoenix", "United States", "America/Phoenix"),
  ("Pittsburgh", "United States", "America/New_York"),
  ("Pomona", "United States", "America/Los_Angeles"),
  ("Port Saint Lucie", "United States", "America/New_York"),
  ("Portland", "United States", "America/Los_Angeles"),
  ("Providence", "United States", "America/New_York"),
  ("Provo", "United States", "America/Denver"),
  ("Pueblo", "United States", "America/Denver"),
  ("Raleigh", "United States", "America/New_York"),
  ("Rancho Cucamonga", "United States", "America/Los_Angeles"),
  ("Reno", "United States", "America/Los_Angeles"),
  ("Richmond", "United States", "America/Los_Angeles"),
  ("Riverside", "United States", "America/Los_Angeles"),
  ("Rochester", "United States", "America/New_York"),
  ("Rochester", "United States", "America/Chicago"),
  ("Rockford", "United States", "America/Chicago"),
  ("Roseville", "United States", "America/Los_Angeles"),
  ("Sacramento", "United States", "America/Los_Angeles"),
  ("Saint Paul", "United States", "America/Chicago"),
  ("Salem", "United States", "America/Los_Angeles"),
  ("Salinas", "United States", "America/Los_Angeles"),
  ("Salt Lake City", "United States", "America/Denver"),
  ("San Bernardino", "United States", "America/Los_Angeles"),
  ("San Diego", "United States", "America/Los_Angeles"),
  ("San Francisco", "United States", "America/Los_Angeles"),
  ("San Jose", "United States", "America/Los_Angeles"),
  ("Santa Ana", "United States", "America/Los_Angeles"),
  ("Santa Clara", "United States", "America/Los_Angeles"),
  ("Santa Clarita", "United States", "America/Los_Angeles"),
  ("Santa Rosa", "United States", "America/Los_Angeles"),
  ("Savannah", "United States", "America/New_York"),
  ("Scottsdale", "United States", "America/Phoenix"),
  ("Seattle", "United States", "America/Los_Angeles"),
  ("Shreveport", "United States", "America/Chicago"),
  ("Simi Valley", "United States", "America/Los_Angeles"),
  ("Sioux Falls", "United States", "America/Chicago"),
  ("South Bend", "United States", "America/Indiana/Indianapolis"),
  ("Spokane", "United States", "America/Los_Angeles"),
  ("Spring Valley", "United States", "America/Los_Angeles"),
  ("Springfield", "United States", "America/Chicago"),
  ("Springfield", "United States", "America/New_York"),
  ("Springfield", "United States", "America/Chicago"),
  ("St. Louis", "United States", "America/Chicago"),
  ("St. Petersburg", "United States", "America/New_York"),
  ("Staten Island", "United States", "America/New_York"),
  ("Sterling Heights", "United States", "America/Detroit"),
  ("Stockton", "United States", "America/Los_Angeles"),
  ("Sunnyvale", "United States", "America/Los_Angeles"),
  ("Sunrise Manor", "United States", "America/Los_Angeles"),
  ("Surprise", "United States", "America/Phoenix"),
  ("Syracuse", "United States", "America/New_York"),
  ("Tacoma", "United States", "America/Los_Angeles"),
  ("Tallahassee", "United States", "America/New_York"),
  ("Tampa", "United States", "America/New_York"),
  ("Temecula", "United States", "America/Los_Angeles"),
  ("Tempe", "United States", "America/Phoenix"),
  ("Tempe Junction", "United States", "America/Phoenix"),
  ("The Bronx", "United States", "America/New_York"),
  ("Thornton", "United States", "America/Denver"),
  ("Thousand Oaks", "United States", "America/Los_Angeles"),
  ("Toledo", "United States", "America/New_York"),
  ("Topeka", "United States", "America/Chicago"),
  ("Torrance", "United States", "America/Los_Angeles"),
  ("Tucson", "United States", "America/Phoenix"),
  ("Tulsa", "United States", "America/Chicago"),
  ("Universal City", "United States", "America/Los_Angeles"),
  ("Vancouver", "United States", "America/Los_Angeles"),
  ("Warren", "United States", "America/Detroit"),
  ("Washington, D.C.", "United States", "America/New_York"),
  ("West Covina", "United States", "America/Los_Angeles"),
  ("West Jordan", "United States", "America/Denver"),
  ("West Valley City", "United States", "America/Denver"),
  ("Westminster", "United States", "America/Denver"),
  ("Wichita", "United States", "America/Chicago"),
  ("Wilmington", "United States", "America/New_York"),
  ("Winston-Salem", "United States", "America/New_York"),
  ("Worcester", "United States", "America/New_York"),
  ("Yonkers", "United States", "America/New_York")
]

def run():
    db = SessionLocal()
    added = skipped = 0
    try:
        existing = {(c.name, c.country) for c in db.query(City).all()}
        seen = set()
        for name, country, timezone in CITIES:
            key = (name, country)
            if key in existing or key in seen:
                skipped += 1
                continue
            seen.add(key)
            db.add(City(name=name, country=country, timezone=timezone))
            added += 1
        db.commit()
        print(f"Done — added: {added}, skipped (already exist): {skipped}, total in DB: {added + skipped + len(existing)}")
    finally:
        db.close()

if __name__ == "__main__":
    run()
